// A QR encoder, ISO/IEC 18004, byte mode at error-correction level L.
//
// # Why this is written here rather than installed
//
// The thing being encoded is a TOTP enrolment secret. A QR of that secret IS
// that secret, so rendering it through an image service would hand a third
// party the second factor for every account that ever enrols — and there is no
// configuration of that which is acceptable.
//
// An npm package would not send it anywhere, but this workspace carries no
// runtime dependencies at all beyond fonts, and the backend wrote its TOTP by
// hand for the same reason: an algorithm that cannot change is a poor thing to
// take a supply chain for.
//
// # What it deliberately does NOT do
//
// Byte mode only, level L only, versions 1 to 10 only. That covers up to 271
// bytes, and an otpauth:// URI is about 150. Numeric and alphanumeric modes
// would pack tighter; kanji mode exists; levels M, Q and H correct more damage.
// None of that is needed to put a secret on a screen for a phone held ten
// centimetres away, and every one of them is another table to get wrong.
//
// A payload too long for version 10 throws rather than silently truncating.
//
// # Typed arrays, and flat ones
//
// `noUncheckedIndexedAccess` is on in this workspace, which makes every index
// into a plain array `T | undefined`. That is the right setting for business
// code and it is noise in a numeric kernel: this file would otherwise be a
// hundred non-null assertions, each of which is a place a real bug could hide.
//
// A `Uint8Array` indexes to `number`, so the codewords, the field tables and
// the module grid are all typed arrays, and the grid is flat with its own
// index helper. The boolean matrix is built once, at the boundary, for the
// renderer.

/** The matrix, row-major. True is a dark module. */
export type QRMatrix = boolean[][];

// Data capacity in bytes, byte mode, level L, versions 1..10.
const CAPACITY = Uint16Array.from([
  17, 32, 53, 78, 106, 134, 154, 192, 230, 271,
]);

// Per version at level L: total codewords, ecc per block, blocks in group 1,
// data codewords per block in group 1, blocks in group 2, data per block in
// group 2. Group 2 is empty except at version 10.
//
// Flat, six entries per version, so a lookup is arithmetic rather than a tuple
// destructure the type checker cannot prove is present.
const BLOCKS = Uint16Array.from([
  26, 7, 1, 19, 0, 0,
  44, 10, 1, 34, 0, 0,
  70, 15, 1, 55, 0, 0,
  100, 20, 1, 80, 0, 0,
  134, 26, 1, 108, 0, 0,
  172, 18, 2, 68, 0, 0,
  196, 20, 2, 78, 0, 0,
  242, 24, 2, 97, 0, 0,
  292, 30, 2, 116, 0, 0,
  346, 18, 2, 68, 2, 69,
]);

// `noUncheckedIndexedAccess` reaches typed arrays too in this TypeScript, so a
// read is `number | undefined` even where the bounds are arithmetic. One reader
// keeps that in a single place rather than scattering assertions through the
// kernel, and it returns zero off the end — which for these tables is only ever
// reachable through a version this file rejects before it gets here.
function u16(table: Uint16Array, at: number): number {
  const v = table[at];
  return v === undefined ? 0 : v;
}

/** The same, for the byte arrays the kernel works in. */
function u8(table: Uint8Array, at: number): number {
  const v = table[at];
  return v === undefined ? 0 : v;
}

interface Layout {
  total: number;
  eccPer: number;
  group1: number;
  data1: number;
  group2: number;
  data2: number;
}

function layoutFor(version: number): Layout {
  const at = (version - 1) * 6;
  return {
    total: u16(BLOCKS, at),
    eccPer: u16(BLOCKS, at + 1),
    group1: u16(BLOCKS, at + 2),
    data1: u16(BLOCKS, at + 3),
    group2: u16(BLOCKS, at + 4),
    data2: u16(BLOCKS, at + 5),
  };
}

// Centres of the alignment patterns, per version. Version 1 has none. Flat and
// zero-terminated for the same reason the table above is flat.
const ALIGNMENT: number[][] = [
  [],
  [6, 18],
  [6, 22],
  [6, 26],
  [6, 30],
  [6, 34],
  [6, 22, 38],
  [6, 24, 42],
  [6, 26, 46],
  [6, 28, 50],
];

function alignmentFor(version: number): number[] {
  const found = ALIGNMENT[version - 1];
  return found === undefined ? [] : found;
}

// The 15-bit format strings for level L, masks 0..7. Published in the standard
// rather than computed, because computing them means implementing BCH for a
// table that cannot change.
const FORMAT_L = Uint16Array.from([
  0x77c4, 0x72f3, 0x7daa, 0x789d, 0x662f, 0x6318, 0x6c41, 0x6976,
]);

// The 18-bit version strings, versions 7..10. Absent below 7, which is what the
// standard says rather than an omission.
const VERSION_BITS = Uint32Array.from([0x07c94, 0x085bc, 0x09a99, 0x0a4d3]);

// --- GF(256) --------------------------------------------------------------
//
// The field the Reed-Solomon codes live in, generated by x^8 + x^4 + x^3 + x^2
// + 1 (0x11d), which is the polynomial the QR standard names.

const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = u8(EXP, i - 255);
}

function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return u8(EXP, u8(LOG, a) + u8(LOG, b));
}

/** The generator polynomial for `degree` error-correction codewords. */
function generator(degree: number): Uint8Array {
  let poly = Uint8Array.from([1]);
  for (let i = 0; i < degree; i++) {
    const next = new Uint8Array(poly.length + 1);
    for (let j = 0; j < poly.length; j++) {
      next[j] = u8(next, j) ^ gfMul(u8(poly, j), 1);
      next[j + 1] = u8(next, j + 1) ^ gfMul(u8(poly, j), u8(EXP, i));
    }
    poly = next;
  }
  return poly;
}

/** The error-correction codewords for one block. */
function ecc(data: Uint8Array, count: number): Uint8Array {
  const gen = generator(count);
  const rem = new Uint8Array(count);
  for (let d = 0; d < data.length; d++) {
    const factor = u8(data, d) ^ u8(rem, 0);
    // Shift left by one, which is what popping the head and pushing a zero
    // does on a plain array.
    rem.copyWithin(0, 1);
    rem[count - 1] = 0;
    for (let i = 0; i < count; i++) {
      rem[i] = u8(rem, i) ^ gfMul(u8(gen, i + 1), factor);
    }
  }
  return rem;
}

// --- encoding -------------------------------------------------------------

/** The smallest version that holds this many bytes, or -1. */
function versionFor(length: number): number {
  for (let v = 0; v < CAPACITY.length; v++) {
    if (length <= u16(CAPACITY, v)) return v + 1;
  }
  return -1;
}

/** The data codewords: mode, length, payload, terminator, padding. */
function codewords(bytes: Uint8Array, version: number): Uint8Array {
  const l = layoutFor(version);
  const dataCount = l.total - l.eccPer * (l.group1 + l.group2);

  const bits: number[] = [];
  const push = (value: number, width: number) => {
    for (let i = width - 1; i >= 0; i--) bits.push((value >> i) & 1);
  };

  push(0b0100, 4); // byte mode
  // The character-count field is eight bits below version 10 and sixteen from
  // version 10 up. Getting this wrong produces a QR that scans as gibberish
  // rather than one that fails to scan.
  push(bytes.length, version < 10 ? 8 : 16);
  for (let i = 0; i < bytes.length; i++) push(u8(bytes, i), 8);

  // Terminator, up to four zero bits, then pad to a byte boundary.
  const capacityBits = dataCount * 8;
  for (let i = 0; i < 4 && bits.length < capacityBits; i++) bits.push(0);
  while (bits.length % 8 !== 0) bits.push(0);

  const out = new Uint8Array(dataCount);
  const written = Math.min(bits.length / 8, dataCount);
  for (let i = 0; i < written; i++) {
    let byte = 0;
    for (let j = 0; j < 8; j++) {
      const bit = bits[i * 8 + j];
      byte = (byte << 1) | (bit === undefined ? 0 : bit);
    }
    out[i] = byte;
  }
  // The two pad bytes the standard names, alternating.
  for (let i = written; i < dataCount; i++) {
    out[i] = (i - written) % 2 === 0 ? 0xec : 0x11;
  }
  return out;
}

/** Data and error-correction codewords, split into blocks and interleaved. */
function interleave(data: Uint8Array, version: number): Uint8Array {
  const l = layoutFor(version);

  const blocks: Uint8Array[] = [];
  let at = 0;
  for (let i = 0; i < l.group1; i++) {
    blocks.push(data.subarray(at, at + l.data1));
    at += l.data1;
  }
  for (let i = 0; i < l.group2; i++) {
    blocks.push(data.subarray(at, at + l.data2));
    at += l.data2;
  }
  const parities = blocks.map((b) => ecc(b, l.eccPer));

  const out = new Uint8Array(l.total);
  let write = 0;

  let longest = 0;
  for (const b of blocks) longest = Math.max(longest, b.length);
  for (let i = 0; i < longest; i++) {
    for (const b of blocks) if (i < b.length) out[write++] = u8(b, i);
  }
  for (let i = 0; i < l.eccPer; i++) {
    for (const p of parities) out[write++] = u8(p, i);
  }
  return out;
}

// --- placement ------------------------------------------------------------
//
// The grid is two flat byte arrays: `dark` holds the module, `fixed` marks the
// function patterns that masking must not touch.

class Grid {
  readonly size: number;
  readonly dark: Uint8Array;
  readonly fixed: Uint8Array;

  constructor(version: number) {
    this.size = version * 4 + 17;
    this.dark = new Uint8Array(this.size * this.size);
    this.fixed = new Uint8Array(this.size * this.size);
  }

  private at(r: number, c: number): number {
    return r * this.size + c;
  }

  inside(r: number, c: number): boolean {
    return r >= 0 && r < this.size && c >= 0 && c < this.size;
  }

  isDark(r: number, c: number): boolean {
    return u8(this.dark, this.at(r, c)) === 1;
  }

  isFixed(r: number, c: number): boolean {
    return u8(this.fixed, this.at(r, c)) === 1;
  }

  /** Writes a module and marks it as a function pattern. */
  fix(r: number, c: number, dark: boolean) {
    if (!this.inside(r, c)) return;
    const i = this.at(r, c);
    this.dark[i] = dark ? 1 : 0;
    this.fixed[i] = 1;
  }

  /** Writes a module without marking it, for data and for the info fields. */
  set(r: number, c: number, dark: boolean) {
    if (!this.inside(r, c)) return;
    this.dark[this.at(r, c)] = dark ? 1 : 0;
  }
}

function placeFinder(g: Grid, row: number, col: number) {
  // The 7x7 eye plus its one-module separator, drawn as a 9x9 window clipped
  // to the grid — simpler than three special cases for the three corners.
  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const onRing = r === 0 || r === 6 || c === 0 || c === 6;
      const inCore = r >= 2 && r <= 4 && c >= 2 && c <= 4;
      const inside = r >= 0 && r <= 6 && c >= 0 && c <= 6;
      g.fix(row + r, col + c, inside && (onRing || inCore));
    }
  }
}

function placeAlignment(g: Grid, version: number) {
  const centres = alignmentFor(version);
  for (const r of centres) {
    for (const c of centres) {
      // Not where a finder already is.
      if (g.isFixed(r, c)) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          const ring = Math.max(Math.abs(dr), Math.abs(dc));
          g.fix(r + dr, c + dc, ring !== 1);
        }
      }
    }
  }
}

function placeTiming(g: Grid) {
  for (let i = 8; i < g.size - 8; i++) {
    const dark = i % 2 === 0;
    g.fix(6, i, dark);
    g.fix(i, 6, dark);
  }
}

/** Marks the format and version areas so data placement skips them. */
function reserveInfo(g: Grid, version: number) {
  for (let i = 0; i < 9; i++) {
    if (!g.isFixed(8, i)) g.fix(8, i, false);
    if (!g.isFixed(i, 8)) g.fix(i, 8, false);
  }
  for (let i = 0; i < 8; i++) {
    if (!g.isFixed(8, g.size - 1 - i)) g.fix(8, g.size - 1 - i, false);
    if (!g.isFixed(g.size - 1 - i, 8)) g.fix(g.size - 1 - i, 8, false);
  }
  // The dark module, always set and not part of the format field.
  g.fix(g.size - 8, 8, true);

  if (version >= 7) {
    for (let i = 0; i < 18; i++) {
      const r = Math.floor(i / 3);
      const c = i % 3;
      g.fix(r, g.size - 11 + c, false);
      g.fix(g.size - 11 + c, r, false);
    }
  }
}

/** Walks the zig-zag and writes the codewords. */
function placeData(g: Grid, bytes: Uint8Array) {
  let bit = 0;
  const next = (): boolean => {
    const index = bit >> 3;
    // Past the end is a zero, which is what the standard's remainder bits are.
    const byte = index < bytes.length ? u8(bytes, index) : 0;
    const value = (byte >> (7 - (bit & 7))) & 1;
    bit++;
    return value === 1;
  };

  let upward = true;
  for (let right = g.size - 1; right > 0; right -= 2) {
    // Column 6 is the vertical timing pattern and is skipped entirely, which
    // shifts every pair to its left by one.
    if (right === 6) right = 5;
    for (let step = 0; step < g.size; step++) {
      const row = upward ? g.size - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (g.isFixed(row, col)) continue;
        g.set(row, col, next());
      }
    }
    upward = !upward;
  }
}

// The eight masks, by their pattern number.
const MASKS: Array<(r: number, c: number) => boolean> = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

function maskFn(index: number): (r: number, c: number) => boolean {
  const found = MASKS[index];
  // Only ever called with 0..7 from the loop below.
  if (found !== undefined) return found;
  // Unreachable: only ever called with 0..7 from the loop below. Written as a
  // value rather than an assertion so there is nothing to be wrong about.
  return (r, c) => (r + c) % 2 === 0;
}

// The finder-like sequences rule 3 looks for: 1:1:3:1:1 with four light
// modules on one side, which is what a reader mistakes for a finder pattern.
const RUN_A = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
const RUN_B = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];

/** The standard's four penalty rules, summed. Lower is better. */
function penalty(m: Uint8Array, n: number): number {
  const at = (r: number, c: number) => u8(m, r * n + c);
  let score = 0;

  // Rule 1: runs of five or more of the same colour, in rows and in columns.
  for (let pass = 0; pass < 2; pass++) {
    for (let a = 0; a < n; a++) {
      let run = 1;
      for (let b = 1; b < n; b++) {
        const here = pass === 0 ? at(a, b) : at(b, a);
        const before = pass === 0 ? at(a, b - 1) : at(b - 1, a);
        if (here === before) {
          run++;
          if (run === 5) score += 3;
          else if (run > 5) score += 1;
        } else {
          run = 1;
        }
      }
    }
  }

  // Rule 2: every 2x2 block of one colour.
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const v = at(r, c);
      if (v === at(r, c + 1) && v === at(r + 1, c) && v === at(r + 1, c + 1)) {
        score += 3;
      }
    }
  }

  // Rule 3.
  for (let pass = 0; pass < 2; pass++) {
    for (let a = 0; a < n; a++) {
      for (let b = 0; b + 11 <= n; b++) {
        let hitA = true;
        let hitB = true;
        for (let k = 0; k < 11; k++) {
          const v = pass === 0 ? at(a, b + k) : at(b + k, a);
          if (v !== RUN_A[k]) hitA = false;
          if (v !== RUN_B[k]) hitB = false;
        }
        if (hitA) score += 40;
        if (hitB) score += 40;
      }
    }
  }

  // Rule 4: how far the proportion of dark modules is from half.
  let dark = 0;
  for (let i = 0; i < m.length; i++) dark += u8(m, i);
  const percent = (dark * 100) / (n * n);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

function writeFormat(m: Uint8Array, n: number, mask: number) {
  const bits = u16(FORMAT_L, mask);
  const set = (r: number, c: number, dark: boolean) => {
    m[r * n + c] = dark ? 1 : 0;
  };

  for (let i = 0; i < 15; i++) {
    const dark = ((bits >> i) & 1) === 1;
    // The copy beside the top-left finder.
    if (i < 6) set(8, i, dark);
    else if (i === 6) set(8, 7, dark);
    else if (i === 7) set(8, 8, dark);
    else if (i === 8) set(7, 8, dark);
    else set(14 - i, 8, dark);

    // And the split copy beside the other two.
    if (i < 8) set(n - 1 - i, 8, dark);
    else set(8, n - 15 + i, dark);
  }
  set(n - 8, 8, true);
}

function writeVersion(m: Uint8Array, n: number, version: number) {
  if (version < 7) return;
  const found = VERSION_BITS[version - 7];
  const bits = found === undefined ? 0 : found;
  for (let i = 0; i < 18; i++) {
    const dark = ((bits >> i) & 1) === 1 ? 1 : 0;
    const r = Math.floor(i / 3);
    const c = i % 3;
    m[r * n + (n - 11 + c)] = dark;
    m[(n - 11 + c) * n + r] = dark;
  }
}

/**
 * Encodes text as a QR matrix.
 *
 * Throws when the text does not fit version 10 at level L, rather than
 * truncating: a QR that scans to half a URI is worse than none at all, because
 * somebody will scan it and believe it worked.
 */
export function encodeQR(text: string): QRMatrix {
  const bytes = new TextEncoder().encode(text);
  const version = versionFor(bytes.length);
  if (version < 0) {
    throw new Error('too long to encode as a QR at this size');
  }

  const g = new Grid(version);
  placeFinder(g, 0, 0);
  placeFinder(g, 0, g.size - 7);
  placeFinder(g, g.size - 7, 0);
  placeAlignment(g, version);
  placeTiming(g);
  reserveInfo(g, version);
  placeData(g, interleave(codewords(bytes, version), version));

  // Every mask, scored, lowest wins. The standard requires this rather than a
  // fixed choice: a badly masked code is one a phone camera cannot lock onto.
  const n = g.size;
  let best: Uint8Array | null = null;
  let bestScore = Infinity;
  let bestMask = 0;
  for (let mask = 0; mask < 8; mask++) {
    const fn = maskFn(mask);
    const candidate = new Uint8Array(n * n);
    for (let r = 0; r < n; r++) {
      for (let c = 0; c < n; c++) {
        const dark = g.isDark(r, c);
        candidate[r * n + c] =
          g.isFixed(r, c) ? (dark ? 1 : 0) : dark !== fn(r, c) ? 1 : 0;
      }
    }
    const score = penalty(candidate, n);
    // Strictly less, so a tie keeps the lower mask number and the same secret
    // always draws the same picture.
    if (score < bestScore) {
      bestScore = score;
      best = candidate;
      bestMask = mask;
    }
  }

  const chosen = best === null ? new Uint8Array(n * n) : best;
  writeFormat(chosen, n, bestMask);
  writeVersion(chosen, n, version);

  const out: QRMatrix = [];
  for (let r = 0; r < n; r++) {
    const row: boolean[] = [];
    for (let c = 0; c < n; c++) row.push(u8(chosen, r * n + c) === 1);
    out.push(row);
  }
  return out;
}
