// Generates every Biz1core brand file from one description of the mark.
//
//	node scripts/brand-assets.mjs
//
// # Why a generator and not eleven hand-written files
//
// The brief asks for eleven variations of one logo: horizontal, with tagline,
// compact, dark, light, monochrome, print-safe, a favicon, a PWA icon, a
// maskable PWA icon and a Windows .ico. Hand-writing those means eleven copies
// of the same four shapes, and the first time one of them is nudged the set
// stops agreeing with itself -- which is exactly the "duplicate branding
// assets" the brief warns against.
//
// So the geometry is stated once, below, and every file is a projection of it.
// Re-running this after a change to `MARK` rewrites all of them consistently.
//
// # The geometry
//
// Three ascending bars with a curve rising clear above them, on a 32x32 grid.
// The curve clears every bar top by at least two units -- checked, not
// eyeballed -- so at 16px the four shapes stay four shapes instead of merging
// into a smudge. It runs past the tallest bar, which is what makes it read as
// growth rather than as a line struck through a chart.
//
// This must stay in step with shared/src/brand/Logo.tsx, which draws the same
// mark as live SVG for the screen. Two renderings of one drawing: the
// component for the interface, these files for a browser tab, an installer, a
// printed page and a README.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/* -------------------------------------------------------------------------- */
/* the drawing                                                                */
/* -------------------------------------------------------------------------- */

const MARK = {
  bars: [
    { x: 3.6, y: 22, w: 5.4, h: 5.5 },
    { x: 11.3, y: 18, w: 5.4, h: 9.5 },
    { x: 19, y: 13.5, w: 5.4, h: 14 },
  ],
  radius: 1.6,
  curve: 'M3.5 18C9 17 12.5 13 15.5 9.5S23 4 28.5 5',
  curveWidth: 3,
};

/** The two brand accents, as flat values for files that cannot read a CSS variable. */
const PALETTE = {
  light: { bar: '#12876a', curve: '#1f6fe0', word: '#16213a' },
  dark: { bar: '#3fcfa9', curve: '#7db0ff', word: '#f4f7f6' },
  mono: { bar: '#000000', curve: '#000000', word: '#000000' },
  monoInverse: { bar: '#ffffff', curve: '#ffffff', word: '#ffffff' },
};

/** The tile behind the mark on an app icon. The darkest value of the wordmark. */
const TILE = '#16213a';

/**
 * The typeface stack for the wordmark in a standalone file.
 *
 * On screen the wordmark is live text in the application's own IBM Plex Sans
 * (see Logo.tsx). These files are for contexts with no stylesheet -- a README,
 * an installer, a letterhead -- so they name a stack and accept whatever the
 * reader has. The fallbacks are all humanist grotesks of similar width, so the
 * lockup keeps its proportions.
 */
const FONT =
  "'IBM Plex Sans','Segoe UI Variable Text','Segoe UI',system-ui,-apple-system,'Helvetica Neue',Arial,sans-serif";

const BANNER = (what) =>
  `<!-- Biz1core ${what}. Generated by scripts/brand-assets.mjs; not edited by hand. -->`;

/* -------------------------------------------------------------------------- */
/* fragments                                                                  */
/* -------------------------------------------------------------------------- */

function markShapes(colours, dx = 0, dy = 0, scale = 1) {
  const moved = dx || dy ? `translate(${dx} ${dy})` : '';
  const sized = scale === 1 ? '' : `scale(${scale.toFixed(4)})`;
  const t = [moved, sized].filter(Boolean).join(' ');
  const shift = t ? ` transform="${t}"` : '';
  const bars = MARK.bars
    .map(
      (b) =>
        `    <rect x="${b.x}" y="${b.y}" width="${b.w}" height="${b.h}" rx="${MARK.radius}" fill="${colours.bar}"/>`,
    )
    .join('\n');
  return (
    `  <g${shift}>\n` +
    `${bars}\n` +
    `    <path d="${MARK.curve}" stroke="${colours.curve}" stroke-width="${MARK.curveWidth}" stroke-linecap="round" fill="none"/>\n` +
    `  </g>`
  );
}

/** The mark alone, on a transparent ground. */
function markFile(colours, what) {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" role="img" aria-label="Biz1core">`,
    `  <title>Biz1core</title>`,
    BANNER(what),
    markShapes(colours),
    `</svg>`,
    ``,
  ].join('\n');
}

/**
 * The horizontal lockup: mark, then the word, optionally then the tagline.
 *
 * The "1" is its own <tspan> so it carries the accent, which is the one
 * detail that makes the name read as Biz-1-core rather than as a typo.
 */
function lockupFile(colours, { tagline }, what) {
  // The mark is set taller than the word's cap height on purpose. Its ink runs
  // on a diagonal, so a mark matched to the cap height reads as a scribble
  // beside eight bold letters; a quarter more height balances the two.
  const mark = tagline ? 44 : 36;
  const gap = Math.round(mark * 0.33);
  const textX = mark + gap;

  const height = tagline ? 64 : 48;
  // Wide enough for the longest line at its own size, measured rather than
  // guessed: a tagline clipped to "One Solution for Complete Business Managem"
  // is the one failure a logo file must not ship with.
  const width = tagline ? 360 : 204;

  const word =
    `  <text x="${textX}" y="${tagline ? 33 : 34}" font-family="${FONT}" font-size="32" font-weight="700" ` +
    `letter-spacing="-0.6" fill="${colours.word}">Biz<tspan fill="${colours.curve}">1</tspan>core</text>`;

  const strap = tagline
    ? `\n  <text x="${textX}" y="52" font-family="${FONT}" font-size="13" font-weight="500" ` +
      `letter-spacing="0.1" fill="${colours.word}" opacity="0.72">One Solution for Complete Business Management.</text>`
    : '';

  const name = `Biz1core${tagline ? ' — One Solution for Complete Business Management.' : ''}`;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" role="img" aria-label="${name}">`,
    `  <title>${name}</title>`,
    BANNER(what),
    markShapes(colours, 0, (height - mark) / 2, mark / 32),
    word + strap,
    `</svg>`,
    ``,
  ].join('\n');
}

/**
 * The app icon: the mark on a filled tile.
 *
 * `inset` is the safe-area margin. A launcher may crop an installed icon to a
 * circle or a squircle, so the maskable version draws the mark smaller inside
 * the same tile rather than relying on the launcher to be gentle.
 */
function appIconFile(what, { inset = 0, radius = 0.22 } = {}) {
  const scale = (32 - inset * 2) / 32;
  const g =
    inset === 0
      ? markShapes(PALETTE.dark)
      : `  <g transform="translate(${inset} ${inset}) scale(${scale.toFixed(4)})">\n` +
        markShapes(PALETTE.dark)
          .split('\n')
          .slice(1, -1)
          .join('\n') +
        `\n  </g>`;

  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" role="img" aria-label="Biz1core">`,
    `  <title>Biz1core</title>`,
    BANNER(what),
    `  <rect width="32" height="32" rx="${(32 * radius).toFixed(2)}" fill="${TILE}"/>`,
    g,
    `</svg>`,
    ``,
  ].join('\n');
}

/* -------------------------------------------------------------------------- */
/* .ico                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Writes a Windows icon containing PNG images.
 *
 * ICO has carried PNG payloads since Vista and every target here -- the Tauri
 * installer, the Windows taskbar, a browser asking for /favicon.ico -- reads
 * them. So each size is a PNG and the file is a six-byte header, a sixteen-byte
 * directory entry per size, and the payloads.
 */
function ico(images) {
  const count = images.length;
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(count, 4);

  const entries = [];
  let offset = 6 + count * 16;
  for (const { size, data } of images) {
    const e = Buffer.alloc(16);
    // 256 is stored as 0: the field is one byte.
    e.writeUInt8(size >= 256 ? 0 : size, 0);
    e.writeUInt8(size >= 256 ? 0 : size, 1);
    e.writeUInt8(0, 2); // palette entries: none, it is a PNG
    e.writeUInt8(0, 3); // reserved
    e.writeUInt16LE(1, 4); // colour planes
    e.writeUInt16LE(32, 6); // bits per pixel
    e.writeUInt32LE(data.length, 8);
    e.writeUInt32LE(offset, 12);
    entries.push(e);
    offset += data.length;
  }

  return Buffer.concat([header, ...entries, ...images.map((i) => i.data)]);
}

/* -------------------------------------------------------------------------- */
/* run                                                                        */
/* -------------------------------------------------------------------------- */

async function put(rel, contents) {
  const path = join(root, rel);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents);
  const size = Buffer.isBuffer(contents) ? contents.length : Buffer.byteLength(contents);
  console.log(`  ${rel.padEnd(52)} ${String(size).padStart(7)} bytes`);
}

/** Rasterises an SVG at one size. `density` keeps the curve's ends smooth. */
async function png(svg, size) {
  return sharp(Buffer.from(svg), { density: 384 }).resize(size, size).png({ compressionLevel: 9 }).toBuffer();
}

const BRAND = 'web-next/public/brand';

console.log('Biz1core brand assets\n');

// --- scalable, for the screen and for anybody who needs a file --------------
await put(`${BRAND}/mark.svg`, markFile(PALETTE.light, 'compact mark, light surfaces'));
await put(`${BRAND}/mark-dark.svg`, markFile(PALETTE.dark, 'compact mark, dark surfaces'));
await put(`${BRAND}/mark-mono.svg`, markFile(PALETTE.mono, 'compact mark, monochrome / print'));

await put(
  `${BRAND}/biz1core-logo.svg`,
  lockupFile(PALETTE.light, { tagline: false }, 'horizontal logo, light surfaces'),
);
await put(
  `${BRAND}/biz1core-logo-dark.svg`,
  lockupFile(PALETTE.dark, { tagline: false }, 'horizontal logo, dark surfaces'),
);
await put(
  `${BRAND}/biz1core-logo-tagline.svg`,
  lockupFile(PALETTE.light, { tagline: true }, 'horizontal logo with tagline'),
);
await put(
  `${BRAND}/biz1core-logo-tagline-dark.svg`,
  lockupFile(PALETTE.dark, { tagline: true }, 'horizontal logo with tagline, dark surfaces'),
);
await put(
  `${BRAND}/biz1core-logo-mono.svg`,
  lockupFile(PALETTE.mono, { tagline: false }, 'horizontal logo, monochrome / print-safe'),
);

// --- the app's own identity -------------------------------------------------
const appIcon = appIconFile('app icon');
const maskable = appIconFile('app icon, maskable safe area', { inset: 3.2, radius: 0.5 });
await put(`${BRAND}/app-icon.svg`, appIcon);
await put(`${BRAND}/app-icon-maskable.svg`, maskable);

// The PWA manifest and the <link rel=icon> fallbacks. The paths are the ones
// the manifest and the root layout already name, so nothing has to be rewired.
await put('web-next/public/icons/icon-192.png', await png(appIcon, 192));
await put('web-next/public/icons/icon-512.png', await png(appIcon, 512));
await put('web-next/public/icons/icon-512-maskable.png', await png(maskable, 512));
await put('web-next/public/favicon.ico', ico([
  { size: 16, data: await png(appIcon, 16) },
  { size: 32, data: await png(appIcon, 32) },
  { size: 48, data: await png(appIcon, 48) },
]));

// The till is a desktop application: Windows wants an .ico for the installer,
// the taskbar and the window, and Tauri points at exactly one file.
await put('pos/src-tauri/icons/icon.ico', ico([
  { size: 16, data: await png(appIcon, 16) },
  { size: 32, data: await png(appIcon, 32) },
  { size: 48, data: await png(appIcon, 48) },
  { size: 64, data: await png(appIcon, 64) },
  { size: 128, data: await png(appIcon, 128) },
  { size: 256, data: await png(appIcon, 256) },
]));
await put('pos/src-tauri/icons/icon.png', await png(appIcon, 512));

// The till's own web root, for the browser tab during `npm run dev`.
await put('pos/public/favicon.ico', ico([
  { size: 16, data: await png(appIcon, 16) },
  { size: 32, data: await png(appIcon, 32) },
]));
await put('pos/public/brand/app-icon.svg', appIcon);

console.log('\nDone.');
