#!/usr/bin/env bash
#
# Disk and cache maintenance for a Biz1core working copy.
#
# # Why this exists
#
# A Go build cache reached 6.4GB on the development machine, on a disk with
# 40GB free, entirely from ordinary work. Nothing was wrong: that is what a
# build cache does. What was missing was anything that ever looked.
#
# # What it will and will not touch
#
# It touches DISPOSABLE things only — build output, caches, dangling images,
# stopped containers it can identify as this project's. Everything it removes
# can be regenerated by a build.
#
# It never touches:
#
#   * a database, a volume, or anything under a data directory
#   * a running container
#   * the Go MODULE cache by default (that is downloaded source, and removing
#     it costs a network round trip for every dependency; `--deep` opts in)
#   * anything at all when RAWSYST_ENV says production, unless --force
#
# There is deliberately no cleanup on application startup. A build cache
# emptied on every run is a build cache that never helps, and the cost lands on
# whoever is waiting for the build.
#
# # Usage
#
#   scripts/maintenance.sh report            what everything costs, changes nothing
#   scripts/maintenance.sh check             report, and exit 1 if over threshold
#   scripts/maintenance.sh clean             clean only what is over threshold
#   scripts/maintenance.sh clean --all       clean every disposable thing
#   scripts/maintenance.sh clean --deep      also the Go module cache
#   scripts/maintenance.sh clean --dry-run   say what would go, remove nothing
#
# # Thresholds, all overridable from the environment
#
#   RAWSYST_GOCACHE_MAX_MB     default 3000
#   RAWSYST_NPMCACHE_MAX_MB    default 1500
#   RAWSYST_NEXT_MAX_MB        default 1500
#   RAWSYST_DOCKER_MAX_MB      default 4000
#   RAWSYST_LOGS_MAX_MB        default 200
#   RAWSYST_DISK_MIN_FREE_GB   default 10
#   RAWSYST_RAM_MIN_FREE_MB    default 1024 (reported, never acted on)

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

GOCACHE_MAX_MB="${RAWSYST_GOCACHE_MAX_MB:-3000}"
NPMCACHE_MAX_MB="${RAWSYST_NPMCACHE_MAX_MB:-1500}"
NEXT_MAX_MB="${RAWSYST_NEXT_MAX_MB:-1500}"
DOCKER_MAX_MB="${RAWSYST_DOCKER_MAX_MB:-4000}"
LOGS_MAX_MB="${RAWSYST_LOGS_MAX_MB:-200}"
DISK_MIN_FREE_GB="${RAWSYST_DISK_MIN_FREE_GB:-10}"
# Memory is reported and never acted on, so this only decides when the
# report says to run the heavy suites one at a time.
RAM_MIN_FREE_MB="${RAWSYST_RAM_MIN_FREE_MB:-1024}"

ACTION="${1:-report}"
shift || true

ALL=0; DEEP=0; DRY=0; FORCE=0
for arg in "$@"; do
  case "$arg" in
    --all)     ALL=1 ;;
    --deep)    DEEP=1 ;;
    --dry-run) DRY=1 ;;
    --force)   FORCE=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# The one refusal that matters.
#
# A production host has no build cache worth reclaiming and a great deal worth
# keeping, so the safe default is to do nothing there at all. --force exists
# because a build agent may legitimately set RAWSYST_ENV=production.
if [ "${RAWSYST_ENV:-development}" = "production" ] && [ "$FORCE" -ne 1 ]; then
  echo "RAWSYST_ENV=production: refusing to run maintenance."
  echo "Pass --force if this is a build agent rather than a live deployment."
  exit 1
fi

reclaimed_mb=0

# --- measuring ---------------------------------------------------------------

# dir_mb is a directory's size in whole megabytes, or 0 when it is absent.
#
# # Why this is not just `du`
#
# `du -sm` over the Go build cache on Windows did not finish in ten minutes.
# The cache is 24,000 small files and Git Bash's `du` stats each one through
# the POSIX emulation layer, which is where the time goes. The same walk
# through .NET's directory enumerator takes under five seconds — measured, on
# the same directory, on this machine.
#
# So Windows gets PowerShell and everything else gets `du`, which is fast and
# already there.
IS_WINDOWS=0
case "$(uname -s 2>/dev/null || echo unknown)" in
  MINGW*|MSYS*|CYGWIN*) IS_WINDOWS=1 ;;
esac

dir_mb() {
  local path="$1"
  [ -d "$path" ] || { echo 0; return; }

  if [ "$IS_WINDOWS" -eq 1 ] && command -v powershell >/dev/null 2>&1; then
    local win
    win="$(cygpath -w "$path" 2>/dev/null || echo "$path")"
    powershell -NoProfile -NonInteractive -Command "
      \$s=0L
      try {
        foreach(\$f in [System.IO.Directory]::EnumerateFiles('$win','*','AllDirectories')) {
          try { \$s += (New-Object IO.FileInfo \$f).Length } catch {}
        }
      } catch {}
      [math]::Round(\$s/1MB,0)" 2>/dev/null | tr -d '[:space:]' || echo 0
    return
  fi

  du -sm "$path" 2>/dev/null | cut -f1 | tr -d '[:space:]' || echo 0
}

free_gb() {
  df -k "$REPO" 2>/dev/null | awk 'NR==2 {printf "%d", $4/1024/1024}'
}

docker_ok() { command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; }

docker_mb() {
  docker_ok || { echo 0; return; }
  # Reclaimable across images, containers and build cache. Volumes are counted
  # but never acted on.
  #
  # The value and its unit are ONE field -- "6.364GB", with "(13%)" as the
  # second -- so an earlier version tested the unit against the percentage,
  # never matched GB, and reported six gigabytes of build cache as six
  # megabytes. It then cheerfully reported nothing was over threshold.
  docker system df --format '{{.Reclaimable}}' 2>/dev/null |
    awk '{
      f = $1
      v = f; gsub(/[^0-9.]/, "", v)
      if (f ~ /GB/)      v *= 1024
      else if (f ~ /kB/) v /= 1024
      else if (f ~ /MB/) v = v
      else               v /= (1024 * 1024)   # plain bytes
      s += v
    } END { printf "%d", s }'
}

row() { printf "  %-26s %8s MB   %s\n" "$1" "$2" "$3"; }

verdict() {
  local size="$1" max="$2"
  if [ "$size" -gt "$max" ]; then echo "OVER (max ${max})"; else echo "ok (max ${max})"; fi
}

over() {
  local size="$1" max="$2"
  [ "$size" -gt "$max" ]
}

GOCACHE_DIR="$(go env GOCACHE 2>/dev/null || echo '')"
GOMODCACHE_DIR="$(go env GOMODCACHE 2>/dev/null || echo '')"
NPMCACHE_DIR="${npm_config_cache:-${LOCALAPPDATA:-$HOME}/npm-cache}"
[ -d "$NPMCACHE_DIR" ] || NPMCACHE_DIR="$HOME/.npm"


# --- memory, processes and connections --------------------------------------
#
# Disk is what a cache costs; MEMORY is what decides whether a test run
# finishes. These are reported and never acted on: killing a process because it
# looks large is how somebody loses an editor session, and the one process this
# script is entitled to have an opinion about is a duplicate of the project's
# own dev server.

# ram_line reports total, free and used in whole megabytes.
ram_line() {
  if [ "$IS_WINDOWS" -eq 1 ] && command -v powershell >/dev/null 2>&1; then
    powershell -NoProfile -NonInteractive -Command "
      \$os = Get-CimInstance Win32_OperatingSystem
      \$t = [math]::Round(\$os.TotalVisibleMemorySize/1KB,0)
      \$f = [math]::Round(\$os.FreePhysicalMemory/1KB,0)
      Write-Output (\"\$t \$f\")" 2>/dev/null | tr -d '\r'
    return
  fi
  if [ -r /proc/meminfo ]; then
    awk '/MemTotal/ {t=$2} /MemAvailable/ {f=$2} END {printf "%d %d", t/1024, f/1024}' /proc/meminfo
    return
  fi
  echo "0 0"
}

# rawsyst_processes lists this project's own long-running processes.
#
# By NAME, and only the ones this repository starts: an editor's language
# server is also a node process and is none of this script's business.
rawsyst_processes() {
  if [ "$IS_WINDOWS" -eq 1 ] && command -v powershell >/dev/null 2>&1; then
    powershell -NoProfile -NonInteractive -Command "
      Get-Process -Name api,worker,migrate,devseed,postgres -ErrorAction SilentlyContinue |
        ForEach-Object { '{0} {1} {2}' -f \$_.ProcessName, \$_.Id, [math]::Round(\$_.WorkingSet64/1MB,0) }" 2>/dev/null | tr -d '\r'
    return
  fi
  ps -eo comm=,pid=,rss= 2>/dev/null |
    awk '$1 ~ /^(api|worker|migrate|devseed|postgres)$/ {printf "%s %s %d\n", $1, $2, $3/1024}'
}

# db_connections asks the database how many backends are open, and its ceiling.
#
# A pool is a memory reservation as much as a concurrency limit -- every
# connection is a server-side process -- so this is the RAM figure that a
# misconfigured pool moves.
db_connections() {
  command -v psql >/dev/null 2>&1 || { echo ""; return; }
  local dsn="${RAWSYST_DB_DSN:-}"
  [ -n "$dsn" ] || dsn="$(grep -m1 '^RAWSYST_DB_DSN=' "$REPO/backend/.env" 2>/dev/null | cut -d= -f2-)"
  [ -n "$dsn" ] || { echo ""; return; }
  psql "$dsn" -tAc \
    "SELECT count(*) || '/' || current_setting('max_connections') FROM pg_stat_activity" \
    2>/dev/null | tr -d '[:space:]'
}

# docker_images reports what this project's own images weigh.
docker_images() {
  docker_ok || return 0
  docker images --format '{{.Repository}}:{{.Tag}} {{.Size}}' 2>/dev/null |
    grep -E '^(biz1core/|postgres:)' || true
}

measure() {
  GOCACHE_MB="$(dir_mb "$GOCACHE_DIR")"
  GOMOD_MB="$(dir_mb "$GOMODCACHE_DIR")"
  NPM_MB="$(dir_mb "$NPMCACHE_DIR")"
  NEXT_MB=$(( $(dir_mb "$REPO/web-next/.next") + $(dir_mb "$REPO/web/.next") ))
  DIST_MB=$(( $(dir_mb "$REPO/pos/dist") + $(dir_mb "$REPO/backend/bin") ))
  LOGS_MB="$(dir_mb "$REPO/logs")"
  DOCKER_MB="$(docker_mb)"
  FREE_GB="$(free_gb)"
}

report() {
  measure
  echo
  echo "Biz1core maintenance — $(date '+%Y-%m-%d %H:%M')"
  echo
  echo "Disposable, and what each is worth:"
  row "Go build cache"    "$GOCACHE_MB" "$(verdict "$GOCACHE_MB" "$GOCACHE_MAX_MB")"
  row "npm cache"         "$NPM_MB"     "$(verdict "$NPM_MB" "$NPMCACHE_MAX_MB")"
  row "Next build output" "$NEXT_MB"    "$(verdict "$NEXT_MB" "$NEXT_MAX_MB")"
  row "Docker reclaimable" "$DOCKER_MB" "$(verdict "$DOCKER_MB" "$DOCKER_MAX_MB")"
  row "Build artefacts"   "$DIST_MB"    "always safe to remove"
  row "Logs"              "$LOGS_MB"    "$(verdict "$LOGS_MB" "$LOGS_MAX_MB")"
  echo
  echo "Kept unless asked (--deep):"
  row "Go module cache"   "$GOMOD_MB"   "downloaded source; removing it costs a re-download"
  echo
  printf "  %-26s %8s GB   %s\n" "Free on this volume" "$FREE_GB" \
    "$( [ "$FREE_GB" -lt "$DISK_MIN_FREE_GB" ] && echo "LOW (min ${DISK_MIN_FREE_GB})" || echo "ok (min ${DISK_MIN_FREE_GB})" )"
  echo

  # --- memory and processes, which no amount of cache cleaning changes ------

  local total free used
  read -r total free <<<"$(ram_line)"
  total="${total:-0}"; free="${free:-0}"
  used=$(( total - free ))
  echo "Memory:"
  if [ "$total" -gt 0 ]; then
    printf "  %-26s %8s MB   of %s MB (%s MB free)\n" \
      "In use" "$used" "$total" "$free"
    if [ "$free" -lt "$RAM_MIN_FREE_MB" ]; then
      printf "  %-26s %8s     %s\n" "" "" \
        "LOW (min ${RAM_MIN_FREE_MB} MB) — run the heavy suites one at a time"
    fi
  else
    printf "  %-26s %8s     %s\n" "In use" "?" "not readable on this platform"
  fi

  local procs count
  procs="$(rawsyst_processes)"
  count="$(printf '%s' "$procs" | grep -c . || true)"
  echo
  echo "This project's processes: ${count:-0}"
  if [ -n "$procs" ]; then
    printf '%s\n' "$procs" | while read -r name pid mb; do
      [ -n "$name" ] || continue
      printf "  %-14s pid %-8s %6s MB\n" "$name" "$pid" "$mb"
    done
    # The one duplicate this script is entitled to name. Two API processes on
    # one machine means the second could not bind and the first is serving
    # something a developer may not have meant to leave running.
    local apis
    apis="$(printf '%s\n' "$procs" | awk '$1 == "api"' | grep -c . || true)"
    if [ "${apis:-0}" -gt 1 ]; then
      echo "  WARNING: ${apis} API processes are running. Only one can hold :8080."
    fi
  fi

  local conns
  conns="$(db_connections)"
  if [ -n "$conns" ]; then
    echo
    printf "  %-26s %8s     %s\n" "Database connections" "$conns" \
      "every one is a server-side process"
  fi

  local images
  images="$(docker_images)"
  if [ -n "$images" ]; then
    echo
    echo "Images:"
    printf '%s\n' "$images" | while read -r name size; do
      [ -n "$name" ] || continue
      printf "  %-40s %s\n" "$name" "$size"
    done
  fi
  echo
}

# --- cleaning ----------------------------------------------------------------

say() {
  if [ "$DRY" -eq 1 ]; then echo "  would $1"; else echo "  $1"; fi
}

# run executes unless this is a dry run.
run() { [ "$DRY" -eq 1 ] || "$@" >/dev/null 2>&1; }

clean_go() {
  local before="$GOCACHE_MB"
  say "clean the Go build cache (${before} MB)"
  run go clean -cache
  # The test cache is separate and much smaller, but a stale one is also how a
  # test "passes" without running.
  run go clean -testcache
  reclaimed_mb=$(( reclaimed_mb + before ))
}

clean_gomod() {
  local before="$GOMOD_MB"
  say "clean the Go MODULE cache (${before} MB) — every dependency re-downloads next build"
  run go clean -modcache
  reclaimed_mb=$(( reclaimed_mb + before ))
}

clean_npm() {
  local before="$NPM_MB"
  say "clean the npm cache (${before} MB)"
  run npm cache clean --force
  reclaimed_mb=$(( reclaimed_mb + before ))
}

clean_next() {
  local before="$NEXT_MB"
  say "remove Next build output (${before} MB)"
  run rm -rf "$REPO/web-next/.next" "$REPO/web/.next"
  reclaimed_mb=$(( reclaimed_mb + before ))
}

clean_artifacts() {
  local before="$DIST_MB"
  [ "$before" -gt 0 ] || return 0
  say "remove build artefacts (${before} MB)"
  run rm -rf "$REPO/pos/dist" "$REPO/backend/bin"
  reclaimed_mb=$(( reclaimed_mb + before ))
}

# clean_docker removes only what Docker itself calls reclaimable, and never
# volumes.
#
# `docker system prune` without --volumes leaves every named volume alone,
# which is what stands between this and somebody's database. It is spelled out
# rather than relied upon: the flags here are the whole safety argument.
clean_docker() {
  docker_ok || { echo "  docker is not running; skipped"; return 0; }
  local before="$DOCKER_MB"
  say "prune dangling images, stopped containers, unused networks and build cache (${before} MB)"
  run docker container prune -f
  run docker image prune -f
  run docker network prune -f
  run docker builder prune -f
  reclaimed_mb=$(( reclaimed_mb + before ))
  echo "  volumes were NOT touched; a database lives in one"
}

clean_logs() {
  local before="$LOGS_MB"
  [ "$before" -gt 0 ] || return 0
  say "remove log files older than 14 days (${before} MB now)"
  [ "$DRY" -eq 1 ] || find "$REPO/logs" -type f -mtime +14 -delete 2>/dev/null
}

# --- entry points -------------------------------------------------------------

case "$ACTION" in
  report)
    report
    ;;

  check)
    report
    fail=0
    over "$GOCACHE_MB" "$GOCACHE_MAX_MB" && fail=1
    over "$NPM_MB" "$NPMCACHE_MAX_MB" && fail=1
    over "$NEXT_MB" "$NEXT_MAX_MB" && fail=1
    over "$DOCKER_MB" "$DOCKER_MAX_MB" && fail=1
    over "$LOGS_MB" "$LOGS_MAX_MB" && fail=1
    [ "$FREE_GB" -lt "$DISK_MIN_FREE_GB" ] && fail=1
    if [ "$fail" -eq 1 ]; then
      echo "Over threshold. Run: scripts/maintenance.sh clean"
      exit 1
    fi
    echo "Everything is within its threshold."
    ;;

  clean)
    measure
    echo
    if [ "$DRY" -eq 1 ]; then echo "Dry run — nothing will be removed."; fi
    echo "Cleaning:"
    if [ "$ALL" -eq 1 ]; then
      clean_go; clean_npm; clean_next; clean_artifacts; clean_docker; clean_logs
      [ "$DEEP" -eq 1 ] && clean_gomod
    else
      over "$GOCACHE_MB" "$GOCACHE_MAX_MB" && clean_go
      over "$NPM_MB" "$NPMCACHE_MAX_MB"    && clean_npm
      over "$NEXT_MB" "$NEXT_MAX_MB"       && clean_next
      over "$DOCKER_MB" "$DOCKER_MAX_MB"   && clean_docker
      over "$LOGS_MB" "$LOGS_MAX_MB"       && clean_logs
      [ "$DEEP" -eq 1 ] && over "$GOMOD_MB" 2000 && clean_gomod
      if [ "$reclaimed_mb" -eq 0 ]; then
        echo "  nothing is over its threshold; nothing removed"
      fi
    fi
    echo
    if [ "$DRY" -eq 1 ]; then
      echo "Would reclaim about ${reclaimed_mb} MB."
    else
      echo "Reclaimed about ${reclaimed_mb} MB."
      report
    fi
    ;;

  *)
    echo "usage: scripts/maintenance.sh {report|check|clean} [--all] [--deep] [--dry-run] [--force]" >&2
    exit 2
    ;;
esac
