package zatca

// The transform chain applied to an invoice before it is hashed or stamped.
//
// # Provenance
//
// Read on 2026-08-23 from the primary source, not from a summary of it:
//
//	ZATCA, "Security Features Implementation Standards to the E-Invoicing
//	resolution", Version 1.1, dated 2022-06-24, §2.3.3 "Structure of the
//	Cryptographic Stamp in XAdES format", and §3 "Previous invoice hash
//	specification".
//	https://zatca.gov.sa/ar/E-Invoicing/SystemsDevelopers/Documents/
//	20220624_ZATCA_Electronic_Invoice_Security_Features_Implementation_Standards.pdf
//
// This closes SA.ZATCA.XML_CANONICALIZATION, which had been open since 0044
// split it out of the hash rule. 0044's note said the canonicalisation "is not
// verified" and that "two implementations that agree on the algorithm and
// disagree on the canonical form produce different hashes". The form is below,
// and it is quoted rather than described.
//
// # What §2.3.3 states
//
// The ds:Transforms element on the first ds:Reference carries four transforms,
// in this order. The three XPath transforms use the 1999 XPath algorithm and
// each removes one subtree; the fourth is the canonicalisation.
//
//	<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
//	  <ds:XPath>not(//ancestor-or-self::ext:UBLExtensions)</ds:XPath>
//	<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
//	  <ds:XPath>not(//ancestor-or-self::cac:Signature)</ds:XPath>
//	<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
//	  <ds:XPath>not(//ancestor-or-self::cac:AdditionalDocumentReference[cbc:ID='QR'])</ds:XPath>
//	<ds:Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
//
// The three removals are what make the hash stable: the signature block, the
// UBL extension that carries it, and the QR reference are all written INTO the
// document after the hash is taken, so hashing them would be circular.
//
// §3, in full: "The hash of the previous invoice is generated by applying the
// same transform as is used for the cryptographic stamp and as specified in
// section 2.3.3 and taking the sha256 algorithm."
//
// # Why this file holds constants rather than an implementation
//
// Applying the chain needs a UBL 2.1 document to apply it TO, and that document
// is specified by a different standard — the Electronic Invoice XML
// Implementation Standard, 72 pages and 119 rule families — which remains open
// as SA.ZATCA.UBL_FIELD_SET. More to the point, ZATCA's own validator is the
// only thing that can confirm a generated document is right, and it ships in
// the Fatoora SDK, which is behind a login this project does not have.
//
// So these are recorded as verified fact, with the citation, and the code that
// will consume them is not written yet. A canonicaliser that had never been run
// against ZATCA's validator would be a guess wearing the costume of an
// implementation, which is the whole reason UnimplementedHasher exists.

// TransformXPath1999 is the XPath transform algorithm the three removals use.
const TransformXPath1999 = "http://www.w3.org/TR/1999/REC-xpath-19991116"

// CanonicalizationC14N11 is the canonical form the chain ends in: W3C
// Canonical XML 1.1. NOT exclusive c14n, and not the 2001 version — both are
// commonly assumed and neither is what §2.3.3 names.
const CanonicalizationC14N11 = "http://www.w3.org/2006/12/xml-c14n11"

// HashAlgorithm is the digest, per §2.3.3 ("sha256 in this case") and §3.
const HashAlgorithm = "sha256"

// SignedPropertiesType is the Type attribute on the second ds:Reference,
// quoted from §2.3.3: "http://uri.etsi.org/01903#SignedProperties."
//
// The trailing full stop in the document is sentence punctuation, not part of
// the URI; every other reference to this URI in ETSI EN 319 132-1 ends at
// "SignedProperties".
const SignedPropertiesType = "http://uri.etsi.org/01903#SignedProperties"

// InvoiceTransforms are the XPath removals, in the order §2.3.3 lists them.
//
// Order is part of the specification rather than an implementation detail: a
// transform chain is applied in sequence, and two chains with the same members
// in a different order can produce different bytes.
var InvoiceTransforms = []string{
	"not(//ancestor-or-self::ext:UBLExtensions)",
	"not(//ancestor-or-self::cac:Signature)",
	"not(//ancestor-or-self::cac:AdditionalDocumentReference[cbc:ID='QR'])",
}
