package zatca

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"encoding/asn1"
	"encoding/base64"
	"io"
	"math/big"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The CSR is checked against OpenSSL rather than against a golden blob.
//
// A golden blob would be generated by the same encoder it is meant to test,
// which proves only that the code still does what it did yesterday. OpenSSL is
// an independent ASN.1 parser that had no part in producing these bytes, and it
// is the same tool the Developer Portal Manual tells the reader to use — so if
// it disagrees with us about what we emitted, we are wrong.
//
// Where OpenSSL is not installed the parse tests skip and the structural tests
// still run.

// stubSigner stands in for the device's security module.
//
// It cannot compute a real secp256k1 signature and does not try: Go's standard
// library has no such curve, which is exactly why BuildCSR takes a
// crypto.Signer instead of generating a key. What is under test is the
// ENCODING, and every parser reads the signature as an opaque bit string.
type stubSigner struct{ pub *ecdsa.PublicKey }

func (s stubSigner) Public() crypto.PublicKey { return s.pub }

func (s stubSigner) Sign(io.Reader, []byte, crypto.SignerOpts) ([]byte, error) {
	// A well-formed ECDSA-Sig-Value, so the enclosing structure is valid DER.
	return asn1.Marshal(struct{ R, S *big.Int }{big.NewInt(0x1234), big.NewInt(0x5678)})
}

// secp256k1TestKey returns a public key on the right curve.
//
// The point is the curve's own generator, which is on the curve by definition.
// No arithmetic is ever performed on this CurveParams — that would panic, since
// crypto/elliptic's generic implementation assumes a = -3 — and none is needed:
// BuildCSR reads the parameters and the coordinates and encodes them.
func secp256k1TestKey() *ecdsa.PublicKey {
	curve := &elliptic.CurveParams{
		P:       secp256k1P,
		N:       secp256k1N,
		B:       secp256k1B,
		Gx:      secp256k1Gx,
		Gy:      secp256k1Gy,
		BitSize: 256,
		Name:    "secp256k1",
	}
	return &ecdsa.PublicKey{Curve: curve, X: secp256k1Gx, Y: secp256k1Gy}
}

func validSubject() CSRSubject {
	return CSRSubject{
		CommonName:         "TERMINAL-01",
		OrganizationName:   "Jarir",
		OrganizationalUnit: "Riyadh Branch",
		CountryCode:        "SA",
		EGSSerialNumber:    "1-RawSyst|2-POS|3-0000000001",
		OrganizationID:     "310122393500003",
		InvoiceTypes:       "1100",
		Location:           "Riyadh",
		Industry:           "Retail",
	}
}

func buildTestCSR(t *testing.T) []byte {
	t.Helper()
	csr, err := BuildCSR(validSubject(), TemplateNameTSTZATCACodeSigning,
		stubSigner{pub: secp256k1TestKey()})
	if err != nil {
		t.Fatalf("building the request: %v", err)
	}
	return csr
}

// opensslText runs `openssl req -noout -text` over the request.
//
// -noout -text parses and prints; it does not verify the signature, which the
// stub signer cannot produce.
func opensslText(t *testing.T, csr []byte) string {
	t.Helper()
	bin, err := exec.LookPath("openssl")
	if err != nil {
		t.Skip("openssl is not installed; skipping the independent parse")
	}
	path := filepath.Join(t.TempDir(), "taxpayer.csr")
	if err := os.WriteFile(path, csr, 0o600); err != nil {
		t.Fatalf("writing the request: %v", err)
	}
	out, err := exec.Command(bin, "req", "-in", path, "-noout", "-text").CombinedOutput()
	if err != nil {
		t.Fatalf("openssl refused the request: %v\n%s", err, out)
	}
	return string(out)
}

func TestTheRequestCarriesTheSubjectTheConfigFileSpecifies(t *testing.T) {
	text := opensslText(t, buildTestCSR(t))

	// The [dn] section, in the order page 91 lists it.
	for _, want := range []string{
		"C=SA",
		"OU=Riyadh Branch",
		"O=Jarir",
		"CN=TERMINAL-01",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("the subject is missing %q\n%s", want, text)
		}
	}
}

func TestTheRequestIsOnTheOnlyCurveZATCAAccepts(t *testing.T) {
	text := opensslText(t, buildTestCSR(t))

	if !strings.Contains(text, "secp256k1") {
		t.Errorf("the request does not name secp256k1\n%s", text)
	}
	// A P-256 request would also say "id-ecPublicKey" and "(256 bit)", so the
	// curve name is the assertion that distinguishes them.
	if !strings.Contains(text, "id-ecPublicKey") {
		t.Errorf("the request does not carry an EC public key\n%s", text)
	}
	if !strings.Contains(text, "ecdsa-with-SHA256") {
		t.Errorf("the request is not signed ecdsa-with-SHA256\n%s", text)
	}
}

func TestTheRequestCarriesTheCertificateTemplateExtension(t *testing.T) {
	text := opensslText(t, buildTestCSR(t))

	// The OID read off page 91 of the manual, and the value from page 95.
	if !strings.Contains(text, "1.3.6.1.4.1.311.20.2") {
		t.Errorf("the certificateTemplateName extension is missing\n%s", text)
	}
	if !strings.Contains(text, TemplateNameTSTZATCACodeSigning) {
		t.Errorf("the template name is not %q\n%s", TemplateNameTSTZATCACodeSigning, text)
	}
}

func TestTheRequestCarriesTheAlternativeNamesZATCAReadsTheTaxpayerFrom(t *testing.T) {
	text := opensslText(t, buildTestCSR(t))

	// Asserted against the DirName line alone, not the whole dump. "Riyadh"
	// also appears in the subject as part of the branch name, so searching the
	// full text would pass even if the alternative names were empty.
	var dirName string
	for _, line := range strings.Split(text, "\n") {
		if i := strings.Index(line, "DirName:"); i >= 0 {
			dirName = strings.TrimSpace(line[i:])
		}
	}
	if dirName == "" {
		t.Fatalf("the request carries no subjectAltName directory name\n%s", text)
	}

	// These five are the whole reason the alt_names section exists: without
	// them ZATCA has the device but not the taxpayer, the VAT number or which
	// document types the unit may issue.
	for _, want := range []string{
		"serialNumber=1-RawSyst|2-POS|3-0000000001", // the EGS serial
		"UID=310122393500003",                       // the VAT registration
		"title=1100",                                // the TSCZ functionality map
		"registeredAddress=Riyadh",
		"businessCategory=Retail",
	} {
		if !strings.Contains(dirName, want) {
			t.Errorf("the alternative names are missing %q\n%s", want, dirName)
		}
	}
}

func TestTheRequestRefusesAKeyOnTheWrongCurve(t *testing.T) {
	// P-256 is the curve a Go implementer reaches for by habit. It produces a
	// perfectly well-formed CSR that ZATCA refuses, and the refusal does not
	// say why — so it is caught here instead.
	wrong := &ecdsa.PublicKey{
		Curve: elliptic.P256(),
		X:     elliptic.P256().Params().Gx,
		Y:     elliptic.P256().Params().Gy,
	}
	_, err := BuildCSR(validSubject(), TemplateNameTSTZATCACodeSigning, stubSigner{pub: wrong})
	if err == nil {
		t.Fatal("a P-256 key produced a certificate request")
	}
	if !strings.Contains(err.Error(), "secp256k1") {
		t.Errorf("the error does not name the curve: %v", err)
	}
}

func TestTheRequestRefusesATemplateNameZATCADoesNotPublish(t *testing.T) {
	_, err := BuildCSR(validSubject(), "ZATCA-Code-Signing-v2", stubSigner{pub: secp256k1TestKey()})
	if err == nil {
		t.Fatal("an invented template name was accepted")
	}
}

func TestTheSubjectRefusesValuesZATCAWouldReject(t *testing.T) {
	cases := []struct {
		name   string
		mutate func(*CSRSubject)
	}{
		{"a VAT number that is not 15 digits", func(s *CSRSubject) { s.OrganizationID = "3101223935003" }},
		{"a VAT number not starting with 3", func(s *CSRSubject) { s.OrganizationID = "410122393500003" }},
		{"a VAT number not ending with 3", func(s *CSRSubject) { s.OrganizationID = "310122393500004" }},
		{"a VAT number containing a letter", func(s *CSRSubject) { s.OrganizationID = "31012239350000X" }},
		{"an invoice type that is all zeros", func(s *CSRSubject) { s.InvoiceTypes = "0000" }},
		{"an invoice type using a digit other than 0 or 1", func(s *CSRSubject) { s.InvoiceTypes = "1102" }},
		{"an invoice type of the wrong length", func(s *CSRSubject) { s.InvoiceTypes = "110" }},
		{"a three-letter country code", func(s *CSRSubject) { s.CountryCode = "SAU" }},
		{"a serial number missing a segment", func(s *CSRSubject) { s.EGSSerialNumber = "1-RawSyst|2-POS" }},
		{"a serial number with segments out of order", func(s *CSRSubject) { s.EGSSerialNumber = "2-POS|1-RawSyst|3-1" }},
		{"no organization name", func(s *CSRSubject) { s.OrganizationName = "" }},
		{"no branch location", func(s *CSRSubject) { s.Location = "" }},
	}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			s := validSubject()
			c.mutate(&s)
			if err := s.Validate(); err == nil {
				t.Errorf("%s was accepted", c.name)
			}
		})
	}
}

func TestTheSubjectAcceptsAConformantUnit(t *testing.T) {
	if err := validSubject().Validate(); err != nil {
		t.Fatalf("a conformant subject was refused: %v", err)
	}
}

func TestTheAPIBodyCarriesBase64OfThePEMBlockNotTheDER(t *testing.T) {
	encoded := EncodeCSRForAPI(buildTestCSR(t))

	decoded, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		t.Fatalf("the encoded request is not base64: %v", err)
	}
	// Page 96's Postman screenshot shows a "csr" value beginning
	// LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNU, which is the armour line and
	// not DER. Base64 of the DER would begin MII...
	if !strings.HasPrefix(string(decoded), "-----BEGIN CERTIFICATE REQUEST-----") {
		t.Errorf("the body is not base64 of the PEM block, it begins %.40q", decoded)
	}
	if !strings.HasPrefix(encoded, "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNU") {
		t.Errorf("the body does not match the prefix the manual shows: %.44q", encoded)
	}
}

func TestEveryPublishedTemplateNameIsAccepted(t *testing.T) {
	// PREZATCA-Code-Signing is the FATOORA Simulation value recorded by
	// SA.ZATCA.CSR_CERTIFICATE_TEMPLATE. An earlier draft of BuildCSR knew only
	// the two names printed in the Developer Portal Manual and would have
	// refused every simulation onboarding.
	for _, name := range PublishedTemplateNames {
		if _, err := BuildCSR(validSubject(), name, stubSigner{pub: secp256k1TestKey()}); err != nil {
			t.Errorf("the published template %q was refused: %v", name, err)
		}
	}
}
