package zatca

import (
	"crypto"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"strings"
	"time"

	"github.com/mahedi-emon/rawsyst-pos/backend/internal/platform/errs"
)

// The cryptographic stamp, in XAdES.
//
// # Provenance
//
// Structure from ZATCA, "Security Features Implementation Standards to the
// E-Invoicing resolution", v1.1 (2022-06-24), §2.3.3, which specifies:
//
//   - ds:SignedInfo carrying ds:CanonicalizationMethod, ds:SignatureMethod and
//     exactly TWO ds:Reference elements.
//   - the first Reference has URI="" and the four transforms quoted in
//     canonical.go; sha256; base64 digest.
//   - the second Reference points at the SignedProperties by URI and carries
//     Type="http://uri.etsi.org/01903#SignedProperties".
//   - ds:SignatureValue, base64.
//   - ds:KeyInfo/ds:X509Data/ds:X509Certificate, "a base64-encoded [X509V3]
//     certificate".
//   - ds:Object/QualifyingProperties/SignedProperties/SignedSignatureProperties
//     carrying SigningTime and a signing-certificate reference whose digest is
//     "computed over the entire DER encoded certificate".
//
// §3, in full: "The hash of the previous invoice is generated by applying the
// same transform as is used for the cryptographic stamp and as specified in
// section 2.3.3 and taking the sha256 algorithm." So the invoice digest and the
// PIH are the same computation, which is why both go through CanonicalInvoice.
//
// # What the standard does NOT pin, and how it was settled
//
// §2.3.3 is a schema table, not a worked example. It does not give the literal
// Id values, the ExtensionURI, or the namespace URIs of the UBL signature
// containers. Those are not invented here: they are the values ZATCA's own
// validator accepts, and SignedInvoice is checked against that validator in
// xades_test.go. Where the validator is the only authority, the test that
// consults it is the evidence.

// Algorithm identifiers, from §2.3.3 and the W3C specifications it cites.
const (
	// SignatureMethodECDSASHA256 is the algorithm named for ECDSA over SHA-256.
	SignatureMethodECDSASHA256 = "http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"

	// DigestMethodSHA256 is the digest §2.3.3 names, "sha256 in this case".
	DigestMethodSHA256 = "http://www.w3.org/2001/04/xmlenc#sha256"

	// namespaces used by the signature and its UBL container.
	nsDS    = "http://www.w3.org/2000/09/xmldsig#"
	nsXAdES = "http://uri.etsi.org/01903/v1.3.2#"
	nsSig   = "urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2"
	nsSAC   = "urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2"
	nsSBC   = "urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2"

	// extensionURIXAdES marks the UBL extension carrying an enveloped XAdES
	// signature.
	extensionURIXAdES = "urn:oasis:names:specification:ubl:dsig:enveloped:xades"

	// Identifiers the two references point at.
	signatureID          = "signature"
	signedPropertiesID   = "xadesSignedProperties"
	invoiceSignedDataID  = "invoiceSignedData"
	ublSignatureID       = "urn:oasis:names:specification:ubl:signature:1"
	ublSignatureInvoice  = "urn:oasis:names:specification:ubl:signature:Invoice"
	signedPropertiesType = SignedPropertiesType
)

// Certificate is the stamp certificate and the key that goes with it.
//
// The key is a crypto.Signer and never a raw private key, so a hardware module
// satisfies this exactly as a software key does — which is what the Security
// Features standard's non-exportable-key requirement asks for.
type Certificate struct {
	// DER is the X.509 certificate as issued, in its DER encoding. §2.3.4 is
	// explicit that the digest is "computed over the entire DER encoded
	// certificate", so this is stored as bytes and never re-encoded.
	DER []byte

	// IssuerName and SerialNumber are read off the certificate and carried in
	// the signed properties.
	IssuerName   string
	SerialNumber string

	// NotAfter is the certificate's own expiry, read from its validity field.
	// Zero when it could not be parsed, which is treated as "unknown" rather
	// than "expired" -- guessing would stop a working till.
	NotAfter time.Time

	Signer crypto.Signer
}

// SignedInvoice is everything the terminal produced.
type SignedInvoice struct {
	// XML is the signed document: the original with the signature extension and
	// the QR reference written into it.
	XML []byte

	// InvoiceHash is the base64 SHA-256 of the canonical form — the value that
	// goes in the API body and becomes the next invoice's PIH.
	InvoiceHash string

	// SignatureValue is the base64 DER ECDSA signature over SignedInfo.
	SignatureValue string

	// QR is the base64 TLV payload for the receipt.
	QR string
}

// SignInvoice stamps an unsigned UBL document.
//
// The order is forced by the format and is worth stating, because getting it
// wrong produces a document that verifies against itself and nothing else:
//
//  1. canonicalise the invoice through the transform chain, and hash it
//  2. build SignedProperties, canonicalise it, and hash that
//  3. build SignedInfo carrying both digests, canonicalise it, and SIGN it
//  4. assemble the signature and write it into the document
//
// Step 3 is what is actually signed. Steps 1 and 2 are only inputs to it.
func SignInvoice(
	unsigned []byte, cert Certificate, seller QRSeller, signedAt time.Time,
) (SignedInvoice, error) {
	if len(cert.DER) == 0 {
		return SignedInvoice{}, errs.New(errs.CodeComplianceBlocked,
			"This terminal has no stamp certificate, so it cannot sign. "+
				"Complete e-invoicing onboarding first.")
	}
	if cert.Signer == nil {
		return SignedInvoice{}, errs.New(errs.CodeComplianceBlocked,
			"This terminal has no signing key.")
	}

	// 1. The invoice digest, over the transform chain.
	canonical, err := CanonicalInvoice(unsigned)
	if err != nil {
		return SignedInvoice{}, err
	}
	invoiceDigest := sha256.Sum256(canonical)
	invoiceHash := base64.StdEncoding.EncodeToString(invoiceDigest[:])

	// 2. The signed properties. Their digest is taken over the canonical form
	//    the element has INSIDE the document, not on its own — see
	//    canonicalizeInContext for why the difference decides whether the
	//    signature verifies anywhere but here.
	certDigest := sha256.Sum256(cert.DER)
	signedProperties := buildSignedProperties(
		signedAt.UTC(),
		base64.StdEncoding.EncodeToString(certDigest[:]),
		cert.IssuerName,
		cert.SerialNumber,
	)
	certificate := base64.StdEncoding.EncodeToString(cert.DER)

	draft, err := assembleSigned(unsigned,
		buildSignedInfo(invoiceHash, ""), "", certificate, signedProperties, "")
	if err != nil {
		return SignedInvoice{}, err
	}
	propsCanonical, err := canonicalSubtree(draft, elementWithID(signedPropertiesID))
	if err != nil {
		return SignedInvoice{}, err
	}
	propsDigest := sha256.Sum256(propsCanonical)

	// 3. SignedInfo, carrying both digests, canonicalised in context and signed.
	//    This is the only thing the private key ever sees.
	signedInfo := buildSignedInfo(
		invoiceHash,
		base64.StdEncoding.EncodeToString(propsDigest[:]),
	)
	draft, err = assembleSigned(unsigned, signedInfo, "", certificate, signedProperties, "")
	if err != nil {
		return SignedInvoice{}, err
	}
	infoCanonical, err := canonicalSubtree(draft, elementNamed("SignedInfo"))
	if err != nil {
		return SignedInvoice{}, err
	}
	infoDigest := sha256.Sum256(infoCanonical)

	signature, err := cert.Signer.Sign(rand.Reader, infoDigest[:], crypto.SHA256)
	if err != nil {
		return SignedInvoice{}, errs.New(errs.CodeInternal,
			"The invoice could not be signed by this terminal's key.")
	}
	signatureValue := base64.StdEncoding.EncodeToString(signature)

	// 4. The QR needs the signature and the certificate that made it.
	qr, err := buildInvoiceQR(seller, invoiceDigest[:], signature, cert)
	if err != nil {
		return SignedInvoice{}, err
	}

	// 5. The document as it is sent: the same assembly, now complete.
	final, err := assembleSigned(unsigned, signedInfo, signatureValue, certificate,
		signedProperties, qr)
	if err != nil {
		return SignedInvoice{}, err
	}

	return SignedInvoice{
		XML:            final,
		InvoiceHash:    invoiceHash,
		SignatureValue: signatureValue,
		QR:             qr,
	}, nil
}

// canonicalSubtree parses a document and canonicalises one element in place.
func canonicalSubtree(doc []byte, match func(*xmlElement) bool) ([]byte, error) {
	root, err := parseXML(doc)
	if err != nil {
		return nil, err
	}
	return canonicalizeInContext(root, match)
}

// assembleSigned writes the signature extension and the QR into the document.
//
// Called three times with progressively more filled in, and that repetition is
// deliberate: every digest must be taken over the element as it will actually
// appear, so the same assembly function has to produce the draft that is
// measured and the document that is sent. Two assembly paths would eventually
// disagree by a byte, and the failure would be a rejected invoice rather than a
// failing test.
func assembleSigned(
	unsigned []byte, signedInfo, signatureValue, certificate, signedProperties, qr string,
) ([]byte, error) {
	extension := buildSignatureExtension(signedInfo, signatureValue, certificate, signedProperties)
	return injectSignature(unsigned, extension, qr)
}

// QRSeller is the part of the QR that comes from the invoice rather than the
// signature: tags 1 to 5.
type QRSeller struct {
	Name      string
	VATNumber string
	Timestamp string
	Total     string
	VATTotal  string
}

// buildInvoiceQR assembles all nine tags.
//
// The encodings are not uniform and are documented on each constructor in
// qr.go: tags 1-5 text, tag 6 the base64 text of the digest, tag 7 the base64
// text of the signature, tags 8 and 9 raw DER.
func buildInvoiceQR(s QRSeller, digest, signature []byte, cert Certificate) (string, error) {
	hash, err := QRHash(digest)
	if err != nil {
		return "", err
	}
	stamp, err := QRStampField(signature)
	if err != nil {
		return "", err
	}

	fields := []QRField{
		QRText(QRSellerName, s.Name),
		QRText(QRSellerVAT, s.VATNumber),
		QRText(QRTimestamp, s.Timestamp),
		QRText(QRInvoiceTotal, s.Total),
		QRText(QRVATTotal, s.VATTotal),
		hash,
		stamp,
	}

	// Tag 8 is the certificate's public key, and tag 9 ZATCA's signature over
	// the certificate. Both are read out of the certificate itself rather than
	// passed in, so they cannot disagree with the certificate in KeyInfo.
	if spki := certPublicKeyDER(cert.DER); spki != nil {
		field, err := QRPublicKeyField(spki)
		if err != nil {
			return "", err
		}
		fields = append(fields, field)
	}
	if sig := certSignatureDER(cert.DER); sig != nil {
		field, err := QRCAStampField(sig)
		if err != nil {
			return "", err
		}
		fields = append(fields, field)
	}

	return EncodeQR(fields...)
}

// --- the XML fragments ----------------------------------------------------------
//
// Written as strings rather than marshalled from structs. The bytes are hashed,
// so the exact spelling — prefixes, attribute order, whitespace — is the
// specification, and a marshaller that reorders an attribute for its own reasons
// would silently change a digest.

func buildSignedProperties(at time.Time, certDigest, issuer, serial string) string {
	// Every namespace this fragment needs is declared on it, because it is
	// canonicalised on its own AND as part of the document, and inclusive
	// canonicalisation renders the apex's in-scope namespaces either way. If
	// they were inherited instead, the two canonicalisations would differ and
	// the second reference's digest would never match.
	return `<xades:SignedProperties xmlns:xades="` + nsXAdES + `" xmlns:ds="` + nsDS + `" Id="` + signedPropertiesID + `">
<xades:SignedSignatureProperties>
<xades:SigningTime>` + at.Format("2006-01-02T15:04:05") + `</xades:SigningTime>
<xades:SigningCertificate>
<xades:Cert>
<xades:CertDigest>
<ds:DigestMethod Algorithm="` + DigestMethodSHA256 + `"></ds:DigestMethod>
<ds:DigestValue>` + certDigest + `</ds:DigestValue>
</xades:CertDigest>
<xades:IssuerSerial>
<ds:X509IssuerName>` + escapeXMLText(issuer) + `</ds:X509IssuerName>
<ds:X509SerialNumber>` + escapeXMLText(serial) + `</ds:X509SerialNumber>
</xades:IssuerSerial>
</xades:Cert>
</xades:SigningCertificate>
</xades:SignedSignatureProperties>
</xades:SignedProperties>`
}

func buildSignedInfo(invoiceDigest, propertiesDigest string) string {
	var transforms strings.Builder
	for _, xpath := range InvoiceTransforms {
		transforms.WriteString(`
<ds:Transform Algorithm="` + TransformXPath1999 + `">
<ds:XPath>` + escapeXMLText(xpath) + `</ds:XPath>
</ds:Transform>`)
	}

	return `<ds:SignedInfo xmlns:ds="` + nsDS + `">
<ds:CanonicalizationMethod Algorithm="` + CanonicalizationC14N11 + `"></ds:CanonicalizationMethod>
<ds:SignatureMethod Algorithm="` + SignatureMethodECDSASHA256 + `"></ds:SignatureMethod>
<ds:Reference Id="` + invoiceSignedDataID + `" URI="">
<ds:Transforms>` + transforms.String() + `
<ds:Transform Algorithm="` + CanonicalizationC14N11 + `"></ds:Transform>
</ds:Transforms>
<ds:DigestMethod Algorithm="` + DigestMethodSHA256 + `"></ds:DigestMethod>
<ds:DigestValue>` + invoiceDigest + `</ds:DigestValue>
</ds:Reference>
<ds:Reference Type="` + signedPropertiesType + `" URI="#` + signedPropertiesID + `">
<ds:DigestMethod Algorithm="` + DigestMethodSHA256 + `"></ds:DigestMethod>
<ds:DigestValue>` + propertiesDigest + `</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>`
}

func buildSignatureExtension(signedInfo, signatureValue, certificate, signedProperties string) string {
	return `<ext:UBLExtension>
<ext:ExtensionURI>` + extensionURIXAdES + `</ext:ExtensionURI>
<ext:ExtensionContent>
<sig:UBLDocumentSignatures xmlns:sig="` + nsSig + `" xmlns:sac="` + nsSAC + `" xmlns:sbc="` + nsSBC + `">
<sac:SignatureInformation>
<cbc:ID>` + ublSignatureID + `</cbc:ID>
<sbc:ReferencedSignatureID>` + ublSignatureInvoice + `</sbc:ReferencedSignatureID>
<ds:Signature xmlns:ds="` + nsDS + `" Id="` + signatureID + `">
` + signedInfo + `
<ds:SignatureValue>` + signatureValue + `</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>` + certificate + `</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
<ds:Object>
<xades:QualifyingProperties xmlns:xades="` + nsXAdES + `" Target="signature">
` + signedProperties + `
</xades:QualifyingProperties>
</ds:Object>
</ds:Signature>
</sac:SignatureInformation>
</sig:UBLDocumentSignatures>
</ext:ExtensionContent>
</ext:UBLExtension>`
}

// canonicalFragment canonicalises a standalone element.
func canonicalFragment(fragment string) ([]byte, error) {
	root, err := parseXML([]byte(fragment))
	if err != nil {
		return nil, err
	}
	return canonicalize(root), nil
}

// injectSignature writes the extension and the QR reference into the document.
//
// Textual insertion rather than a re-serialisation of the parsed tree, and
// deliberately: the digest was taken over the document as it stands, and
// re-serialising it risks changing a byte the digest already covers. The two
// things added are exactly the two the transform chain removes again.
func injectSignature(unsigned []byte, extension, qr string) ([]byte, error) {
	doc := string(unsigned)

	// The extension block goes first inside the document element, which is
	// where the UBL schema requires it.
	open := strings.Index(doc, "<Invoice")
	if open < 0 {
		return nil, errs.New(errs.CodeInvalidInput,
			"That document is not a UBL Invoice.")
	}
	end := strings.Index(doc[open:], ">")
	if end < 0 {
		return nil, errs.New(errs.CodeInvalidInput,
			"That document's Invoice element is malformed.")
	}
	at := open + end + 1

	// No surrounding whitespace, and that is load-bearing rather than tidy.
	//
	// The transform chain removes these ELEMENTS. Whitespace inserted alongside
	// them is a TEXT node, is nobody's descendant, and SURVIVES the removal — so
	// a single newline here means the signed document no longer canonicalises to
	// what was signed, and the digest a verifier recomputes does not match the
	// one in the signature. Inserting exactly the elements and nothing else is
	// what makes the removal an exact inverse of the insertion.
	extensions := "<ext:UBLExtensions>" + extension + "</ext:UBLExtensions>"

	// The QR reference sits with the other AdditionalDocumentReference elements.
	// It is added after the PIH so document order stays as the schema expects.
	// The QR reference is written even while empty, so the draft measured for
	// the digests has exactly the shape of the document that is sent. It is
	// removed again by the transform chain either way.
	qrReference := `<cac:AdditionalDocumentReference>` +
		`<cbc:ID>QR</cbc:ID>` +
		`<cac:Attachment>` +
		`<cbc:EmbeddedDocumentBinaryObject mimeCode="text/plain">` + qr +
		`</cbc:EmbeddedDocumentBinaryObject>` +
		`</cac:Attachment>` +
		`</cac:AdditionalDocumentReference>`
	// Before cac:Signature, not before the supplier.
	//
	// UBL 2.1 orders the Invoice element as ... AdditionalDocumentReference*,
	// Signature, AccountingSupplierParty ... so a QR reference written after
	// Signature is schema-invalid. ZATCA's validator says so precisely:
	// "cvc-complex-type.2.4.a: Invalid content was found starting with element
	// AdditionalDocumentReference. One of {Signature, AccountingSupplierParty}
	// is expected."
	marker := "<cac:Signature>"
	supplier := strings.Index(doc, marker)
	if supplier < 0 {
		// A document built before cac:Signature existed still signs correctly;
		// the QR simply goes where the supplier starts.
		marker = "<cac:AccountingSupplierParty>"
		supplier = strings.Index(doc, marker)
	}
	if supplier < 0 {
		return nil, errs.New(errs.CodeInvalidInput,
			"That document has no supplier, so it is not a complete invoice.")
	}

	var out strings.Builder
	out.WriteString(doc[:at])
	out.WriteString(extensions)
	out.WriteString(doc[at:supplier])
	out.WriteString(qrReference)
	out.WriteString(doc[supplier:])
	return []byte(out.String()), nil
}

func escapeXMLText(s string) string {
	return textEscaper.Replace(s)
}

// --- reading the certificate ------------------------------------------------------

// certPublicKeyDER extracts the SubjectPublicKeyInfo, which QR tag 8 carries raw.
func certPublicKeyDER(der []byte) []byte {
	tbs := certTBS(der)
	if tbs == nil {
		return nil
	}
	// Within TBSCertificate the SPKI is the SEQUENCE that begins with an
	// AlgorithmIdentifier naming id-ecPublicKey.
	rest := tbs
	for len(rest) > 0 {
		tag, content, next, err := derParse(rest)
		if err != nil {
			return nil
		}
		if tag == derSequence && containsOID(content, oidECPublicKeyDER) {
			whole := rest[:len(rest)-len(next)]
			return whole
		}
		rest = next
	}
	return nil
}

// certSignatureDER extracts the CA's signature, which QR tag 9 carries raw.
//
// A Certificate is SEQUENCE { tbsCertificate, signatureAlgorithm, signatureValue
// BIT STRING }. The signature is the last element, and the DER ECDSA structure
// sits inside the bit string after its unused-bits octet.
func certSignatureDER(der []byte) []byte {
	_, body, _, err := derParse(der)
	if err != nil {
		return nil
	}
	var last []byte
	rest := body
	for len(rest) > 0 {
		tag, content, next, err := derParse(rest)
		if err != nil {
			return nil
		}
		if tag == derBitStringTag {
			last = content
		}
		rest = next
	}
	if len(last) < 2 || last[0] != 0 {
		return nil
	}
	return last[1:]
}

// certTBS returns the TBSCertificate contents.
func certTBS(der []byte) []byte {
	_, body, _, err := derParse(der)
	if err != nil {
		return nil
	}
	_, tbs, _, err := derParse(body)
	if err != nil {
		return nil
	}
	return tbs
}

// oidECPublicKeyDER is 1.2.840.10045.2.1, encoded.
var oidECPublicKeyDER = []byte{0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01}

func containsOID(haystack, oid []byte) bool {
	return strings.Contains(string(haystack), string(oid))
}

// String keeps a certificate printable without leaking the key.
func (c Certificate) String() string {
	return fmt.Sprintf("Certificate{issuer:%q serial:%s der:%d bytes}",
		c.IssuerName, c.SerialNumber, len(c.DER))
}
