// GENERATED by scripts/generate-api-contract.mjs -- do not edit.
//
// Sources: backend/internal/api/router.go (467 routes,
// 103 route-gated permissions); the permission catalogue and
// role grants seeded in db/migrations (7 further
// action-level permissions); backend/internal/api/entitlement.go (the plan gate).
//
// Regenerate:  npm run gen:contract
// Verify:      npm run check:contract

/** Every permission the product enforces: route-gated and action-level alike. */
export const PERMISSIONS = [
  "accounting.approve",
  "accounting.close_period",
  "accounting.create",
  "accounting.manage_accounts",
  "accounting.reconcile",
  "accounting.reopen_period",
  "accounting.view",
  "approval.decide",
  "approval.manage_rules",
  "approval.view",
  "asset.manage",
  "asset.view",
  "backup.run",
  "backup.view",
  "catalog.create",
  "catalog.delete",
  "catalog.edit",
  "catalog.view",
  "catalog.view_cost_price",
  "catalog.view_profit_margin",
  "compliance.retry_submission",
  "compliance.view",
  "customers.manage",
  "customers.set_credit_limit",
  "customers.view",
  "data.export",
  "data.import",
  "delivery.deliver",
  "delivery.manage",
  "delivery.view",
  "devices.manage",
  "devices.view",
  "document.manage",
  "document.view",
  "einvoicing.manage",
  "einvoicing.onboard",
  "einvoicing.view",
  "expense.manage_heads",
  "expense.record",
  "expense.view",
  "gateway.manage",
  "gateway.view",
  "group.manage",
  "group.view",
  "hr.manage",
  "hr.view",
  "hr.view_pay",
  "identity.create",
  "identity.edit",
  "identity.manage_roles",
  "identity.view",
  "installment.manage",
  "installment.view",
  "integration.manage",
  "integration.view",
  "inventory.adjust_stock",
  "inventory.approve_transfer",
  "inventory.recall_batch",
  "inventory.transfer_stock",
  "inventory.view",
  "investor.manage",
  "investor.view",
  "label.manage",
  "label.print",
  "loyalty.manage",
  "loyalty.view",
  "notification.manage",
  "order.manage",
  "order.view",
  "payroll.approve",
  "payroll.run",
  "payroll.view",
  "portal.manage",
  "portal.view",
  "privacy.manage",
  "privacy.view",
  "promotion.manage",
  "promotion.view",
  "purchasing.approve_bill",
  "purchasing.approve_request",
  "purchasing.award_rfq",
  "purchasing.create_order",
  "purchasing.issue_order",
  "purchasing.manage_rfq",
  "purchasing.manage_suppliers",
  "purchasing.pay_supplier",
  "purchasing.receive_goods",
  "purchasing.record_bill",
  "purchasing.request",
  "purchasing.return_goods",
  "purchasing.view",
  "report.export",
  "report.save",
  "report.view",
  "sales.create",
  "sales.discount",
  "sales.exchange",
  "sales.hold",
  "sales.receive_payment",
  "sales.refund",
  "sales.view",
  "sales.void_draft",
  "serial.manage",
  "serial.view",
  "service.manage",
  "service.view",
  "subscription.view",
  "support.raise",
  "wallet.manage",
  "wallet.view"
] as const;

export type Permission = (typeof PERMISSIONS)[number];

/**
 * The subset that gates a ROUTE.
 *
 * A route guard may only name one of these. The rest are action- and
 * field-level permissions enforced structurally by the backend -- they are the
 * right signal for hiding a discount button or a cost column, and the wrong
 * thing to protect a URL with, because no URL checks them.
 */
export const ROUTE_PERMISSIONS = [
  "accounting.close_period",
  "accounting.create",
  "accounting.manage_accounts",
  "accounting.reconcile",
  "accounting.reopen_period",
  "accounting.view",
  "approval.decide",
  "approval.manage_rules",
  "approval.view",
  "asset.manage",
  "asset.view",
  "backup.run",
  "backup.view",
  "catalog.create",
  "catalog.delete",
  "catalog.edit",
  "catalog.view",
  "compliance.view",
  "customers.manage",
  "customers.set_credit_limit",
  "customers.view",
  "data.export",
  "data.import",
  "delivery.deliver",
  "delivery.manage",
  "delivery.view",
  "devices.manage",
  "devices.view",
  "document.manage",
  "document.view",
  "einvoicing.manage",
  "einvoicing.onboard",
  "einvoicing.view",
  "expense.manage_heads",
  "expense.record",
  "expense.view",
  "gateway.manage",
  "gateway.view",
  "group.manage",
  "group.view",
  "hr.manage",
  "hr.view",
  "hr.view_pay",
  "identity.create",
  "identity.edit",
  "identity.manage_roles",
  "identity.view",
  "installment.manage",
  "installment.view",
  "integration.manage",
  "integration.view",
  "inventory.adjust_stock",
  "inventory.approve_transfer",
  "inventory.recall_batch",
  "inventory.transfer_stock",
  "inventory.view",
  "investor.manage",
  "investor.view",
  "label.manage",
  "label.print",
  "loyalty.manage",
  "loyalty.view",
  "notification.manage",
  "order.manage",
  "order.view",
  "payroll.approve",
  "payroll.run",
  "payroll.view",
  "portal.manage",
  "portal.view",
  "privacy.manage",
  "privacy.view",
  "promotion.manage",
  "promotion.view",
  "purchasing.approve_bill",
  "purchasing.approve_request",
  "purchasing.award_rfq",
  "purchasing.create_order",
  "purchasing.issue_order",
  "purchasing.manage_rfq",
  "purchasing.manage_suppliers",
  "purchasing.pay_supplier",
  "purchasing.receive_goods",
  "purchasing.record_bill",
  "purchasing.request",
  "purchasing.return_goods",
  "purchasing.view",
  "report.export",
  "report.save",
  "report.view",
  "sales.create",
  "sales.exchange",
  "sales.receive_payment",
  "sales.refund",
  "sales.view",
  "serial.manage",
  "serial.view",
  "service.manage",
  "service.view",
  "subscription.view",
  "support.raise",
  "wallet.manage",
  "wallet.view"
] as const;

export type RoutePermission = (typeof ROUTE_PERMISSIONS)[number];

/** The module half of every permission -- `sales` from `sales.refund`. */
export const PERMISSION_MODULES = [
  "accounting",
  "approval",
  "asset",
  "backup",
  "catalog",
  "compliance",
  "customers",
  "data",
  "delivery",
  "devices",
  "document",
  "einvoicing",
  "expense",
  "gateway",
  "group",
  "hr",
  "identity",
  "installment",
  "integration",
  "inventory",
  "investor",
  "label",
  "loyalty",
  "notification",
  "order",
  "payroll",
  "portal",
  "privacy",
  "promotion",
  "purchasing",
  "report",
  "sales",
  "serial",
  "service",
  "subscription",
  "support",
  "wallet"
] as const;

export type PermissionModule = (typeof PERMISSION_MODULES)[number];

/**
 * The plan feature a route group is sold under, if any.
 *
 * A caller without the feature is refused with 402 by the backend regardless of
 * permission, so navigation reads this to explain why a module is unavailable
 * rather than presenting a link that leads to a refusal.
 */
export const FEATURE_OF_ROUTE_GROUP: Readonly<Record<string, string>> =
  {
  "payroll": "payroll",
  "employees": "payroll",
  "leave": "payroll",
  "attendance": "payroll",
  "eosb": "payroll",
  "advances": "payroll",
  "commission-rules": "payroll",
  "loyalty": "loyalty",
  "gift-cards": "loyalty",
  "wallets": "loyalty",
  "store-credit": "loyalty",
  "promotions": "promotions",
  "installments": "installments",
  "service-jobs": "warranty",
  "serials": "warranty",
  "assets": "assets",
  "investors": "assets",
  "analytics": "analytics",
  "approvals": "approvals",
  "approval-rules": "approvals",
  "approval-delegations": "approvals",
  "api-keys": "api_access",
  "webhooks": "webhooks",
  "groups": "consolidation",
  "einvoicing": "einvoicing",
  "labels": "label_studio",
  "orders": "online_orders",
  "deliveries": "online_orders"
};

export interface RouteSpec {
  readonly method: string;
  readonly pattern: string;
  readonly access: 'Public' | 'Authenticated' | 'Permission' | 'SuperAdmin';
  readonly permission: string;
}

/** The whole route table, for the guard tests and the API surface audit. */
export const ROUTES: readonly RouteSpec[] = [
 {
  "method": "GET",
  "pattern": "/healthz",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/readyz",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/metrics",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/meta/version",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/login",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/refresh",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/logout",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/auth/me",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/change-password",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/forgot-password",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/reset-password",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/people",
  "access": "Permission",
  "permission": "identity.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/people/roles",
  "access": "Permission",
  "permission": "identity.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/people",
  "access": "Permission",
  "permission": "identity.create"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/people/{userID}",
  "access": "Permission",
  "permission": "identity.create"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/people/{userID}/active",
  "access": "Permission",
  "permission": "identity.create"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/people/{userID}/reset-password",
  "access": "Permission",
  "permission": "identity.create"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/people/{userID}/roles",
  "access": "Permission",
  "permission": "identity.manage_roles"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/people/roles/{assignmentID}",
  "access": "Permission",
  "permission": "identity.manage_roles"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/catalog/snapshot",
  "access": "Permission",
  "permission": "catalog.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/meta/ping",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/onboarding",
  "access": "Permission",
  "permission": "identity.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/onboarding/steps/{step}",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/onboarding/steps/{step}/complete",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/onboarding/company",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/onboarding/stores",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/catalog/products",
  "access": "Permission",
  "permission": "catalog.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/catalog/products",
  "access": "Permission",
  "permission": "catalog.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/catalog/products/{productID}/matrix",
  "access": "Permission",
  "permission": "catalog.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/catalog/products/{productID}/matrix",
  "access": "Permission",
  "permission": "catalog.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/catalog/variants/{variantID}/prices",
  "access": "Permission",
  "permission": "catalog.edit"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/catalog/variants/{variantID}",
  "access": "Permission",
  "permission": "catalog.delete"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/catalog/scan",
  "access": "Permission",
  "permission": "catalog.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/pos/sales",
  "access": "Permission",
  "permission": "sales.create"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/pos/returns",
  "access": "Permission",
  "permission": "sales.refund"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/pos/sales/{invoiceID}",
  "access": "Permission",
  "permission": "sales.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/pos/sales/lookup",
  "access": "Permission",
  "permission": "sales.refund"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/pos/exchanges",
  "access": "Permission",
  "permission": "sales.exchange"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/pos/sales/{invoiceID}/reprint",
  "access": "Permission",
  "permission": "sales.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/pos/stationery",
  "access": "Permission",
  "permission": "sales.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/pos/sales/{invoiceID}/returnable",
  "access": "Permission",
  "permission": "sales.refund"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/pos/sales/{invoiceID}/signed-document",
  "access": "Permission",
  "permission": "sales.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/pos/counters",
  "access": "Permission",
  "permission": "sales.create"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/pos/counter-sessions",
  "access": "Permission",
  "permission": "sales.create"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/shifts",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/shifts/current",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/shifts/{sessionID}",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/shifts/{sessionID}/x-report",
  "access": "Permission",
  "permission": "report.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/shifts/{sessionID}/cash-drop",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/shifts/{sessionID}/close",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/sync/push",
  "access": "Permission",
  "permission": "sales.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/sync/health",
  "access": "Permission",
  "permission": "sales.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/suppliers",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/suppliers",
  "access": "Permission",
  "permission": "purchasing.manage_suppliers"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/purchasing/suppliers/{supplierID}",
  "access": "Permission",
  "permission": "purchasing.manage_suppliers"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/suppliers/{supplierID}/active",
  "access": "Permission",
  "permission": "purchasing.manage_suppliers"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/orders",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/orders",
  "access": "Permission",
  "permission": "purchasing.create_order"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/orders/{poID}",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/orders/{poID}/issue",
  "access": "Permission",
  "permission": "purchasing.issue_order"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/purchasing/orders/{poID}",
  "access": "Permission",
  "permission": "purchasing.create_order"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/warehouses",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/orders/{poID}/receipts",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/receipts",
  "access": "Permission",
  "permission": "purchasing.receive_goods"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/bills",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/bills",
  "access": "Permission",
  "permission": "purchasing.record_bill"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/bills/{billID}",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/bills/{billID}/approve",
  "access": "Permission",
  "permission": "purchasing.approve_bill"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/bills/{billID}/returnable",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/returns",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/returns",
  "access": "Permission",
  "permission": "purchasing.return_goods"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/returns/{returnID}",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/payments",
  "access": "Permission",
  "permission": "purchasing.pay_supplier"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/payments/{paymentID}/reverse",
  "access": "Permission",
  "permission": "purchasing.pay_supplier"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/ageing",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/requisitions",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/requisitions",
  "access": "Permission",
  "permission": "purchasing.request"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/requisitions/{requisitionID}",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/requisitions/{requisitionID}/decision",
  "access": "Permission",
  "permission": "purchasing.approve_request"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/rfqs",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/rfqs",
  "access": "Permission",
  "permission": "purchasing.manage_rfq"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/rfqs/{rfqID}/comparison",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/rfqs/{rfqID}/quotes",
  "access": "Permission",
  "permission": "purchasing.manage_rfq"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/rfqs/{rfqID}/declines",
  "access": "Permission",
  "permission": "purchasing.manage_rfq"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/rfqs/{rfqID}/award",
  "access": "Permission",
  "permission": "purchasing.award_rfq"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/purchasing/rfqs/{rfqID}/cancel",
  "access": "Permission",
  "permission": "purchasing.manage_rfq"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/purchasing/suppliers/{supplierID}/quotes",
  "access": "Permission",
  "permission": "purchasing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/devices/enrol",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/devices/identity",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/devices/stores",
  "access": "Permission",
  "permission": "devices.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/devices",
  "access": "Permission",
  "permission": "devices.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/devices",
  "access": "Permission",
  "permission": "devices.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/devices/{deviceID}",
  "access": "Permission",
  "permission": "devices.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/devices/{deviceID}",
  "access": "Permission",
  "permission": "devices.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/devices/{deviceID}/enrolment-code",
  "access": "Permission",
  "permission": "devices.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/devices/{deviceID}/settings",
  "access": "Permission",
  "permission": "devices.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/devices/{deviceID}/settings",
  "access": "Permission",
  "permission": "devices.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/devices/{deviceID}/active",
  "access": "Permission",
  "permission": "devices.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/devices/{deviceID}/revoke",
  "access": "Permission",
  "permission": "devices.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/einvoicing/units",
  "access": "Permission",
  "permission": "einvoicing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/einvoicing/units",
  "access": "Permission",
  "permission": "einvoicing.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/einvoicing/units/{unitID}",
  "access": "Permission",
  "permission": "einvoicing.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/einvoicing/units/{unitID}",
  "access": "Permission",
  "permission": "einvoicing.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/einvoicing/units/{unitID}/onboarding",
  "access": "Permission",
  "permission": "einvoicing.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/einvoicing/units/{unitID}/onboarding/compliance",
  "access": "Permission",
  "permission": "einvoicing.onboard"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/einvoicing/units/{unitID}/onboarding/production",
  "access": "Permission",
  "permission": "einvoicing.onboard"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/einvoicing/units/{unitID}/onboarding/renew",
  "access": "Permission",
  "permission": "einvoicing.onboard"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/customers",
  "access": "Permission",
  "permission": "customers.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/customers/snapshot",
  "access": "Permission",
  "permission": "customers.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/customers",
  "access": "Permission",
  "permission": "customers.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/customers/{customerID}",
  "access": "Permission",
  "permission": "customers.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/customers/{customerID}",
  "access": "Permission",
  "permission": "customers.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/customers/{customerID}/credit-limit",
  "access": "Permission",
  "permission": "customers.set_credit_limit"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/customers/{customerID}/active",
  "access": "Permission",
  "permission": "customers.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/customers/{customerID}/ledger",
  "access": "Permission",
  "permission": "customers.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/customers/{customerID}/open-invoices",
  "access": "Permission",
  "permission": "customers.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/receivables/receipts",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/receivables/receipts/{receiptID}/reverse",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/receivables/ageing",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/settlement/pending",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/settlement/batches",
  "access": "Permission",
  "permission": "accounting.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/settlement/batches/{batchID}",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/companies",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/companies/{companyID}/logo",
  "access": "Permission",
  "permission": "identity.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/companies/{companyID}/logo",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/companies/{companyID}/logo",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/companies/{companyID}/logo/image",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/companies/{companyID}/templates",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/companies/{companyID}/templates/{docType}",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/companies/{companyID}/templates/{docType}",
  "access": "Permission",
  "permission": "identity.edit"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/dashboard/overview",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/dashboard/sales",
  "access": "Permission",
  "permission": "sales.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/dashboard/expenses",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/dashboard/compliance",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/expenses",
  "access": "Permission",
  "permission": "expense.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses",
  "access": "Permission",
  "permission": "expense.record"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/expenses/{expenseID}",
  "access": "Permission",
  "permission": "expense.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/expenses/heads",
  "access": "Permission",
  "permission": "expense.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses/heads",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/expenses/heads/{headID}",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses/heads/{headID}/active",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/expenses/accounts",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/expenses/departments",
  "access": "Permission",
  "permission": "expense.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses/departments",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/expenses/departments/{departmentID}",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses/departments/{departmentID}/active",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/expenses/recurring",
  "access": "Permission",
  "permission": "expense.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses/recurring",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses/recurring/{recurringID}/active",
  "access": "Permission",
  "permission": "expense.manage_heads"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/expenses/recurring/generate",
  "access": "Permission",
  "permission": "expense.record"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/locations",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/locations",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/stock/locations/{locationID}",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/locations/{locationID}/active",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/on-hand",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/pos/stock",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/movements",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/adjustments",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/adjustments",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/adjustments/{adjustmentID}",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/counts",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/stock/counts/{adjustmentID}",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/counts/{adjustmentID}/post",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/counts/{adjustmentID}/cancel",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/batches",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/batches/{batchID}/recall",
  "access": "Permission",
  "permission": "inventory.recall_batch"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/production",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/production",
  "access": "Permission",
  "permission": "inventory.adjust_stock"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/production/{productionID}",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/transfers",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/transfers",
  "access": "Permission",
  "permission": "inventory.transfer_stock"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/transfers/{transferID}",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/transfers/{transferID}/approve",
  "access": "Permission",
  "permission": "inventory.approve_transfer"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/transfers/{transferID}/dispatch",
  "access": "Permission",
  "permission": "inventory.transfer_stock"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/transfers/{transferID}/receive",
  "access": "Permission",
  "permission": "inventory.transfer_stock"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/transfers/{transferID}/cancel",
  "access": "Permission",
  "permission": "inventory.transfer_stock"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/dashboard/stock",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/accounting/periods",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/accounting/periods",
  "access": "Permission",
  "permission": "accounting.close_period"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/accounting/periods/{periodID}/close",
  "access": "Permission",
  "permission": "accounting.close_period"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/accounting/periods/{periodID}/reopen",
  "access": "Permission",
  "permission": "accounting.reopen_period"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/accounting/year-end",
  "access": "Permission",
  "permission": "accounting.reopen_period"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/accounting/journals",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/accounting/journals",
  "access": "Permission",
  "permission": "accounting.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/accounting/journals/{journalID}",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/accounting/journals/{journalID}/reverse",
  "access": "Permission",
  "permission": "accounting.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/treasury/accounts",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/treasury/accounts",
  "access": "Permission",
  "permission": "accounting.manage_accounts"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/treasury/accounts/{accountID}/active",
  "access": "Permission",
  "permission": "accounting.manage_accounts"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/treasury/transfers",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/treasury/transfers",
  "access": "Permission",
  "permission": "accounting.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/treasury/statements",
  "access": "Permission",
  "permission": "accounting.reconcile"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/treasury/statements",
  "access": "Permission",
  "permission": "accounting.reconcile"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/treasury/statements/{statementID}",
  "access": "Permission",
  "permission": "accounting.reconcile"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/treasury/statements/{statementID}/reconcile",
  "access": "Permission",
  "permission": "accounting.reconcile"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/treasury/lines/{lineID}/match",
  "access": "Permission",
  "permission": "accounting.reconcile"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/assets",
  "access": "Permission",
  "permission": "asset.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/assets",
  "access": "Permission",
  "permission": "asset.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/assets/depreciate",
  "access": "Permission",
  "permission": "asset.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/assets/{assetID}/dispose",
  "access": "Permission",
  "permission": "asset.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/investors",
  "access": "Permission",
  "permission": "investor.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/investors",
  "access": "Permission",
  "permission": "investor.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/investors/movements",
  "access": "Permission",
  "permission": "investor.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/investors/{investorID}/statement",
  "access": "Permission",
  "permission": "investor.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/promotions",
  "access": "Permission",
  "permission": "promotion.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/promotions",
  "access": "Permission",
  "permission": "promotion.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/promotions/{promotionID}/active",
  "access": "Permission",
  "permission": "promotion.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/promotions/quote",
  "access": "Permission",
  "permission": "promotion.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/orders",
  "access": "Permission",
  "permission": "order.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/orders",
  "access": "Permission",
  "permission": "order.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/orders/{orderID}",
  "access": "Permission",
  "permission": "order.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/orders/{orderID}/advance",
  "access": "Permission",
  "permission": "order.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/orders/{orderID}/invoice",
  "access": "Permission",
  "permission": "sales.create"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/orders/{orderID}/cancel",
  "access": "Permission",
  "permission": "order.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/orders/{orderID}/pick",
  "access": "Permission",
  "permission": "order.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/orders/{orderID}/deliver",
  "access": "Permission",
  "permission": "order.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/orders/{orderID}/documents/{kind}",
  "access": "Permission",
  "permission": "order.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/loyalty/program",
  "access": "Permission",
  "permission": "loyalty.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/loyalty/program",
  "access": "Permission",
  "permission": "loyalty.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/loyalty/members",
  "access": "Permission",
  "permission": "loyalty.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/loyalty/members/{customerID}",
  "access": "Permission",
  "permission": "loyalty.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/loyalty/members/{customerID}/adjust",
  "access": "Permission",
  "permission": "loyalty.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/loyalty/expire",
  "access": "Permission",
  "permission": "loyalty.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/wallets/{customerID}",
  "access": "Permission",
  "permission": "wallet.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/wallets/{customerID}/credit",
  "access": "Permission",
  "permission": "wallet.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/gift-cards",
  "access": "Permission",
  "permission": "wallet.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/gift-cards",
  "access": "Permission",
  "permission": "wallet.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/gift-cards/{cardID}",
  "access": "Permission",
  "permission": "wallet.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/gift-cards/{cardID}/void",
  "access": "Permission",
  "permission": "wallet.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/gift-cards/by-code/{code}",
  "access": "Permission",
  "permission": "wallet.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/store-credit/expire",
  "access": "Permission",
  "permission": "wallet.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/customers/{customerID}/sizes",
  "access": "Permission",
  "permission": "customers.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/customers/{customerID}/sizes",
  "access": "Permission",
  "permission": "customers.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/customers/{customerID}/sizes/{sizeID}",
  "access": "Permission",
  "permission": "customers.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/deliveries",
  "access": "Permission",
  "permission": "delivery.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/deliveries",
  "access": "Permission",
  "permission": "delivery.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/deliveries/{deliveryID}",
  "access": "Permission",
  "permission": "delivery.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/deliveries/{deliveryID}/advance",
  "access": "Permission",
  "permission": "delivery.deliver"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/stock/reservations",
  "access": "Permission",
  "permission": "order.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/stock/reservations/{orderID}",
  "access": "Permission",
  "permission": "order.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/stock/availability",
  "access": "Permission",
  "permission": "inventory.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/serials",
  "access": "Permission",
  "permission": "serial.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/serials",
  "access": "Permission",
  "permission": "serial.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/serials/{serialNo}",
  "access": "Permission",
  "permission": "serial.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/service-jobs",
  "access": "Permission",
  "permission": "service.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/service-jobs",
  "access": "Permission",
  "permission": "service.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/service-jobs/{jobID}",
  "access": "Permission",
  "permission": "service.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/service-jobs/{jobID}",
  "access": "Permission",
  "permission": "service.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/service-jobs/{jobID}/parts",
  "access": "Permission",
  "permission": "service.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/installments/quote",
  "access": "Permission",
  "permission": "installment.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/installments",
  "access": "Permission",
  "permission": "installment.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/installments",
  "access": "Permission",
  "permission": "installment.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/installments/{planID}",
  "access": "Permission",
  "permission": "installment.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/installments/{planID}/collect",
  "access": "Permission",
  "permission": "installment.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/installments/{planID}/cancel",
  "access": "Permission",
  "permission": "installment.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/installments/accrue",
  "access": "Permission",
  "permission": "installment.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/employees",
  "access": "Permission",
  "permission": "hr.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/employees",
  "access": "Permission",
  "permission": "hr.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/employees/expiring",
  "access": "Permission",
  "permission": "hr.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/employees/{employeeID}",
  "access": "Permission",
  "permission": "hr.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/employees/{employeeID}",
  "access": "Permission",
  "permission": "hr.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/employees/{employeeID}/leaving",
  "access": "Permission",
  "permission": "hr.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/attendance",
  "access": "Permission",
  "permission": "hr.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/attendance",
  "access": "Permission",
  "permission": "hr.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/leave",
  "access": "Permission",
  "permission": "hr.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/leave",
  "access": "Permission",
  "permission": "hr.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/leave/{leaveID}/decision",
  "access": "Permission",
  "permission": "hr.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/advances",
  "access": "Permission",
  "permission": "hr.view_pay"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/advances",
  "access": "Permission",
  "permission": "payroll.run"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/payroll",
  "access": "Permission",
  "permission": "payroll.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payroll",
  "access": "Permission",
  "permission": "payroll.run"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/payroll/{runID}",
  "access": "Permission",
  "permission": "payroll.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payroll/{runID}/approve",
  "access": "Permission",
  "permission": "payroll.approve"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payroll/{runID}/pay",
  "access": "Permission",
  "permission": "payroll.approve"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payroll/{runID}/cancel",
  "access": "Permission",
  "permission": "payroll.approve"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payroll/{runID}/wage-file",
  "access": "Permission",
  "permission": "payroll.approve"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/eosb",
  "access": "Permission",
  "permission": "payroll.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/eosb/accrue",
  "access": "Permission",
  "permission": "payroll.run"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/commission-rules",
  "access": "Permission",
  "permission": "payroll.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/commission-rules",
  "access": "Permission",
  "permission": "payroll.run"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/approvals",
  "access": "Permission",
  "permission": "approval.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/approvals/mine",
  "access": "Permission",
  "permission": "approval.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/approvals/{requestID}",
  "access": "Permission",
  "permission": "approval.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/approvals/{requestID}/decide",
  "access": "Permission",
  "permission": "approval.decide"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/approvals/escalate",
  "access": "Permission",
  "permission": "approval.decide"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/approval-rules",
  "access": "Permission",
  "permission": "approval.manage_rules"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/approval-rules",
  "access": "Permission",
  "permission": "approval.manage_rules"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/approval-rules/{ruleID}/active",
  "access": "Permission",
  "permission": "approval.manage_rules"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/approval-delegations",
  "access": "Permission",
  "permission": "approval.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/approval-delegations",
  "access": "Permission",
  "permission": "approval.decide"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/notifications",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/notifications/unread",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/notifications/read",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/notifications/{notificationID}/read",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/notifications/announce",
  "access": "Permission",
  "permission": "notification.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/notifications/preferences",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/notifications/preferences",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/webhooks",
  "access": "Permission",
  "permission": "integration.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/webhooks",
  "access": "Permission",
  "permission": "integration.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/webhooks/{endpointID}/active",
  "access": "Permission",
  "permission": "integration.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/webhooks/{endpointID}/deliveries",
  "access": "Permission",
  "permission": "integration.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/api-keys",
  "access": "Permission",
  "permission": "integration.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/api-keys",
  "access": "Permission",
  "permission": "integration.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/api-keys/{keyID}",
  "access": "Permission",
  "permission": "integration.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/imports/shapes",
  "access": "Permission",
  "permission": "data.import"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/imports",
  "access": "Permission",
  "permission": "data.import"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/imports",
  "access": "Permission",
  "permission": "data.import"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/imports/{importID}",
  "access": "Permission",
  "permission": "data.import"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/imports/{importID}/validate",
  "access": "Permission",
  "permission": "data.import"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/imports/{importID}/commit",
  "access": "Permission",
  "permission": "data.import"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/imports/{importID}/cancel",
  "access": "Permission",
  "permission": "data.import"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/exports/{kind}",
  "access": "Permission",
  "permission": "data.export"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/backups/health",
  "access": "Permission",
  "permission": "backup.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/backups",
  "access": "Permission",
  "permission": "backup.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/backups",
  "access": "Permission",
  "permission": "backup.run"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/backups/{backupID}/finish",
  "access": "Permission",
  "permission": "backup.run"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/backups/{backupID}/verify",
  "access": "Permission",
  "permission": "backup.run"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/support/tickets",
  "access": "Permission",
  "permission": "support.raise"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/support/tickets",
  "access": "Permission",
  "permission": "support.raise"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/support/tickets/{ticketID}",
  "access": "Permission",
  "permission": "support.raise"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/support/tickets/{ticketID}/reply",
  "access": "Permission",
  "permission": "support.raise"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/support/tickets/{ticketID}/close",
  "access": "Permission",
  "permission": "support.raise"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/labels/scheme",
  "access": "Permission",
  "permission": "label.print"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/labels/scheme",
  "access": "Permission",
  "permission": "label.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/labels/barcodes",
  "access": "Permission",
  "permission": "label.manage"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/labels/barcodes/{variantID}",
  "access": "Permission",
  "permission": "label.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/labels/templates",
  "access": "Permission",
  "permission": "label.print"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/labels/templates",
  "access": "Permission",
  "permission": "label.manage"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/labels/templates/{templateID}",
  "access": "Permission",
  "permission": "label.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/labels/templates/{templateID}",
  "access": "Permission",
  "permission": "label.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/labels/print",
  "access": "Permission",
  "permission": "label.print"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/portal/code",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/portal/session",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/portal/supplier/session",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/portal/session",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/me",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/invoices",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/orders",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/warranty",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/addresses",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/portal/addresses",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/portal/addresses/{addressID}",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/returns",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/portal/returns",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/supplier/home",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/supplier/orders",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/supplier/orders/{orderID}",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/portal/supplier/orders/{orderID}/respond",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/supplier/bills",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/supplier/rfqs",
  "access": "Public",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/contacts",
  "access": "Permission",
  "permission": "portal.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/portal/contacts",
  "access": "Permission",
  "permission": "portal.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/portal/contacts/{contactID}",
  "access": "Permission",
  "permission": "portal.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/portal/return-requests",
  "access": "Permission",
  "permission": "portal.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/portal/return-requests/{returnID}/decide",
  "access": "Permission",
  "permission": "portal.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/auth/mfa",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/mfa/begin",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/mfa/complete",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/mfa/disable",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/auth/mfa/recovery-codes",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/auth/sessions",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/auth/sessions/{sessionID}",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/permissions",
  "access": "Permission",
  "permission": "identity.manage_roles"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/roles",
  "access": "Permission",
  "permission": "identity.manage_roles"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/roles/{roleID}",
  "access": "Permission",
  "permission": "identity.manage_roles"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/roles/{roleID}",
  "access": "Permission",
  "permission": "identity.manage_roles"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/roles/{roleID}",
  "access": "Permission",
  "permission": "identity.manage_roles"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/live",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/payment-providers",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/payment-gateways",
  "access": "Permission",
  "permission": "gateway.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payment-gateways",
  "access": "Permission",
  "permission": "gateway.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/payment-gateways/{gatewayID}",
  "access": "Permission",
  "permission": "gateway.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/payment-gateways/{gatewayID}",
  "access": "Permission",
  "permission": "gateway.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/payment-gateways/{gatewayID}",
  "access": "Permission",
  "permission": "gateway.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payment-gateways/{gatewayID}/check",
  "access": "Permission",
  "permission": "gateway.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payment-gateways/{gatewayID}/charge",
  "access": "Permission",
  "permission": "sales.receive_payment"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/payment-attempts",
  "access": "Permission",
  "permission": "gateway.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/payment-attempts/{attemptID}/refund",
  "access": "Permission",
  "permission": "sales.refund"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/subscription",
  "access": "Permission",
  "permission": "subscription.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/subscription/invoices",
  "access": "Permission",
  "permission": "subscription.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/subscription/entitlements",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/plans",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/groups",
  "access": "Permission",
  "permission": "group.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/groups",
  "access": "Permission",
  "permission": "group.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/groups/{groupID}",
  "access": "Permission",
  "permission": "group.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/groups/{groupID}",
  "access": "Permission",
  "permission": "group.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/groups/{groupID}",
  "access": "Permission",
  "permission": "group.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/groups/{groupID}/members",
  "access": "Permission",
  "permission": "group.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/groups/{groupID}/members/{memberID}",
  "access": "Permission",
  "permission": "group.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/groups/{groupID}/statement",
  "access": "Permission",
  "permission": "group.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/groups/{groupID}/intercompany",
  "access": "Permission",
  "permission": "group.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/groups/intercompany",
  "access": "Permission",
  "permission": "group.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/saved",
  "access": "Permission",
  "permission": "report.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/reports/saved",
  "access": "Permission",
  "permission": "report.save"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/reports/saved/{savedID}",
  "access": "Permission",
  "permission": "report.save"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/workforce",
  "access": "Permission",
  "permission": "report.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/{kind}/export",
  "access": "Permission",
  "permission": "report.export"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/documents",
  "access": "Permission",
  "permission": "document.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/documents",
  "access": "Permission",
  "permission": "document.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/documents/{documentID}/file",
  "access": "Permission",
  "permission": "document.view"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/documents/{documentID}",
  "access": "Permission",
  "permission": "document.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/consents",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/consents",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/consents/{consentID}/withdraw",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/requests",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/requests",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/requests/{dsrID}/extend",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/requests/{dsrID}/close",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/incidents",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/incidents",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/incidents/{incidentID}/notify",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/incidents/{incidentID}/close",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/activities",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/privacy/activities",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "DELETE",
  "pattern": "/api/v1/privacy/activities/{activityID}",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/retention",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/privacy/retention",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/holds",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/holds",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "POST",
  "pattern": "/api/v1/privacy/holds/{holdID}/release",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/destructions",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/settings",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/privacy/settings",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/subprocessors",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/privacy/disclosure",
  "access": "Permission",
  "permission": "privacy.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/privacy/disclosure",
  "access": "Permission",
  "permission": "privacy.manage"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/compliance",
  "access": "Permission",
  "permission": "compliance.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/exchange-rates",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/exchange-rates",
  "access": "Permission",
  "permission": "accounting.create"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/search",
  "access": "Authenticated",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/analytics/kpis",
  "access": "Permission",
  "permission": "report.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/analytics/movers",
  "access": "Permission",
  "permission": "report.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/analytics/forecast",
  "access": "Permission",
  "permission": "report.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/analytics/profitability",
  "access": "Permission",
  "permission": "report.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/audit",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/trial-balance",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/profit-and-loss",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/balance-sheet",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/cash-flow",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/reports/vat-return",
  "access": "Permission",
  "permission": "accounting.view"
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/tenants/{tenantID}/subscription",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/platform/tenants/{tenantID}/subscription",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/tenants/{tenantID}/limits",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/platform/tenants/{tenantID}/limits",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/platform/tenants/{tenantID}/features",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/tenants/{tenantID}/invoices",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/invoices/{subInvoiceID}/settle",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/dunning",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "PUT",
  "pattern": "/api/v1/platform/subprocessors",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/rules",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/rules",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/jurisdictions",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/jurisdictions",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/jurisdictions/import",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/jurisdictions/{jurisdictionID}/rates",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/jurisdictions/rates",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/jurisdictions/rates/review",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/jurisdictions/rates/activate",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/jurisdictions/rates/verify",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/health",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/tenants",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/jobs/failed",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/jobs/{jobID}/retry",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "GET",
  "pattern": "/api/v1/platform/support",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/support/{ticketID}/reply",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/tenants",
  "access": "SuperAdmin",
  "permission": ""
 },
 {
  "method": "POST",
  "pattern": "/api/v1/platform/users/{userID}/reset-password",
  "access": "SuperAdmin",
  "permission": ""
 }
];
