-- California's published sales tax rates, from CDTFA's own quarterly file.
--
-- 0109 seeded California's 7.25% statewide share alone and left it
-- deliberately unverified, because a sale resolving only that rate would
-- undercharge wherever a district applies -- which is most of the state. This
-- is the missing half: the 541 locations CDTFA publishes, each with the share
-- levied on top of the state's.
--
-- Source: California Department of Tax and Fee Administration, "California
-- City & County Sales & Use Tax Rates", the file SalesTaxRates07-01-26.xlsx
-- linked from https://www.cdtfa.ca.gov/taxes-and-fees/sales-use-tax-rates.htm
-- and effective 1 July 2026. Downloaded and converted on 2026-09-04; the
-- quarter after it (10-01-26) is not published yet.
--
-- # These are shares, not the rates CDTFA prints
--
-- CDTFA publishes a COMBINED rate per location: Alameda reads 10.75%, and
-- that figure already contains the statewide 7.25%. This product sums a
-- jurisdiction chain instead, so storing 10.75% under a state already holding
-- 7.25% would charge 18%. Each row below is therefore the published combined
-- rate LESS the statewide rate -- Alameda 0.035 -- and the chain adds back to
-- exactly what CDTFA printed, which is the number a shop is audited against.
--
-- The arithmetic is done by cmd/cdtfaimport, which reads the authority's file
-- and refuses rather than guessing if any location falls below the statewide
-- base. Next quarter's file goes through the same tool and is applied through
-- POST /api/v1/platform/jurisdictions/import, which supersedes these rows by
-- date rather than editing them.
--
-- # Still unverified, on purpose
--
-- verified_on is NULL on every row. The figures are the authority's own, but
-- nobody has yet put their name to the conversion, and the product refuses an
-- unverified rate rather than charging it. So this does not let a Californian
-- shop trade -- it means the operator confirming these rates is checking 541
-- rows that are already filled in, instead of typing them.
--
-- # Five counties are absent, and that is what CDTFA says
--
-- Del Norte, Kern, Monterey, Santa Cruz and Yuba publish no county-wide
-- figure: their row carries an empty rate and a note directing the reader to
-- the city or the unincorporated area. Each of those appears here as
-- "<name> County Unincorporated Area" plus its cities. A county-wide rate
-- invented for them would undercharge every sale in them.

CREATE TEMP TABLE cdtfa_load (
  level text NOT NULL,
  code  text NOT NULL,
  name  text NOT NULL,
  rate  numeric(9,6) NOT NULL
) ON COMMIT DROP;

INSERT INTO cdtfa_load (level, code, name, rate) VALUES
  ('city', 'CA-ADELANTO', 'Adelanto', 0.005),
  ('city', 'CA-AGOURA-HILLS', 'Agoura Hills', 0.025),
  ('city', 'CA-ALAMEDA', 'Alameda', 0.035),
  ('county', 'CA-ALAMEDA-COUNTY', 'Alameda County', 0.03),
  ('city', 'CA-ALBANY', 'Albany', 0.035),
  ('city', 'CA-ALHAMBRA', 'Alhambra', 0.0325),
  ('city', 'CA-ALISO-VIEJO', 'Aliso Viejo', 0.005),
  ('county', 'CA-ALPINE-COUNTY', 'Alpine County', 0),
  ('city', 'CA-ALTURAS', 'Alturas', 0),
  ('city', 'CA-AMADOR-CITY', 'Amador City', 0.0075),
  ('county', 'CA-AMADOR-COUNTY', 'Amador County', 0.005),
  ('city', 'CA-AMERICAN-CANYON', 'American Canyon', 0.005),
  ('city', 'CA-ANAHEIM', 'Anaheim', 0.005),
  ('city', 'CA-ANDERSON', 'Anderson', 0.005),
  ('city', 'CA-ANGELS-CAMP', 'Angels Camp', 0.015),
  ('city', 'CA-ANTIOCH', 'Antioch', 0.025),
  ('city', 'CA-APPLE-VALLEY', 'Apple Valley', 0.015),
  ('city', 'CA-ARCADIA', 'Arcadia', 0.0325),
  ('city', 'CA-ARCATA', 'Arcata', 0.03),
  ('city', 'CA-ARROYO-GRANDE', 'Arroyo Grande', 0.015),
  ('city', 'CA-ARTESIA', 'Artesia', 0.0325),
  ('city', 'CA-ARVIN', 'Arvin', 0.01),
  ('city', 'CA-ATASCADERO', 'Atascadero', 0.015),
  ('city', 'CA-ATHERTON', 'Atherton', 0.02125),
  ('city', 'CA-ATWATER', 'Atwater', 0.015),
  ('city', 'CA-AUBURN', 'Auburn', 0),
  ('city', 'CA-AVALON', 'Avalon', 0.03),
  ('city', 'CA-AVENAL', 'Avenal', 0.01),
  ('city', 'CA-AZUSA', 'Azusa', 0.035),
  ('city', 'CA-BAKERSFIELD', 'Bakersfield', 0.01),
  ('city', 'CA-BALDWIN-PARK', 'Baldwin Park', 0.0325),
  ('city', 'CA-BANNING', 'Banning', 0.005),
  ('city', 'CA-BARSTOW', 'Barstow', 0.015),
  ('city', 'CA-BEAUMONT', 'Beaumont', 0.005),
  ('city', 'CA-BELL', 'Bell', 0.025),
  ('city', 'CA-BELL-GARDENS', 'Bell Gardens', 0.0325),
  ('city', 'CA-BELLFLOWER', 'Bellflower', 0.0325),
  ('city', 'CA-BELMONT', 'Belmont', 0.02625),
  ('city', 'CA-BELVEDERE', 'Belvedere', 0.01),
  ('city', 'CA-BENICIA', 'Benicia', 0.02375),
  ('city', 'CA-BERKELEY', 'Berkeley', 0.03),
  ('city', 'CA-BEVERLY-HILLS', 'Beverly Hills', 0.025),
  ('city', 'CA-BIG-BEAR-LAKE', 'Big Bear Lake', 0.005),
  ('city', 'CA-BIGGS', 'Biggs', 0.01),
  ('city', 'CA-BISHOP', 'Bishop', 0.015),
  ('city', 'CA-BLUE-LAKE', 'Blue Lake', 0.025),
  ('city', 'CA-BLYTHE', 'Blythe', 0.015),
  ('city', 'CA-BRADBURY', 'Bradbury', 0.025),
  ('city', 'CA-BRAWLEY', 'Brawley', 0.015),
  ('city', 'CA-BREA', 'Brea', 0.005),
  ('city', 'CA-BRENTWOOD', 'Brentwood', 0.015),
  ('city', 'CA-BRISBANE', 'Brisbane', 0.02625),
  ('city', 'CA-BUELLTON', 'Buellton', 0.005),
  ('city', 'CA-BUENA-PARK', 'Buena Park', 0.015),
  ('city', 'CA-BURBANK', 'Burbank', 0.0325),
  ('city', 'CA-BURLINGAME', 'Burlingame', 0.02375),
  ('county', 'CA-BUTTE-COUNTY', 'Butte County', 0.01),
  ('city', 'CA-CALABASAS', 'Calabasas', 0.025),
  ('county', 'CA-CALAVERAS-COUNTY', 'Calaveras County', 0.01),
  ('city', 'CA-CALEXICO', 'Calexico', 0.01),
  ('city', 'CA-CALIFORNIA-CITY', 'California City', 0.01),
  ('city', 'CA-CALIMESA', 'Calimesa', 0.005),
  ('city', 'CA-CALIPATRIA', 'Calipatria', 0.005),
  ('city', 'CA-CALISTOGA', 'Calistoga', 0.005),
  ('city', 'CA-CAMARILLO', 'Camarillo', 0),
  ('city', 'CA-CAMPBELL', 'Campbell', 0.0325),
  ('city', 'CA-CANYON-LAKE', 'Canyon Lake', 0.005),
  ('city', 'CA-CAPITOLA', 'Capitola', 0.02),
  ('city', 'CA-CARLSBAD', 'Carlsbad', 0.005),
  ('city', 'CA-CARMELBYTHESEA', 'Carmel-by-the-Sea', 0.02),
  ('city', 'CA-CARPINTERIA', 'Carpinteria', 0.0175),
  ('city', 'CA-CARSON', 'Carson', 0.0325),
  ('city', 'CA-CATHEDRAL-CITY', 'Cathedral City', 0.02),
  ('city', 'CA-CERES', 'Ceres', 0.01125),
  ('city', 'CA-CERRITOS', 'Cerritos', 0.025),
  ('city', 'CA-CHICO', 'Chico', 0.02),
  ('city', 'CA-CHINO', 'Chino', 0.015),
  ('city', 'CA-CHINO-HILLS', 'Chino Hills', 0.005),
  ('city', 'CA-CHOWCHILLA', 'Chowchilla', 0.015),
  ('city', 'CA-CHULA-VISTA', 'Chula Vista', 0.015),
  ('city', 'CA-CITRUS-HEIGHTS', 'Citrus Heights', 0.005),
  ('city', 'CA-CITY-OF-COMMERCE', 'City of Commerce', 0.0325),
  ('city', 'CA-CITY-OF-INDUSTRY', 'City of Industry', 0.025),
  ('city', 'CA-CLAREMONT', 'Claremont', 0.025),
  ('city', 'CA-CLAYTON', 'Clayton', 0.015),
  ('city', 'CA-CLEARLAKE', 'Clearlake', 0.015),
  ('city', 'CA-CLOVERDALE', 'Cloverdale', 0.0275),
  ('city', 'CA-CLOVIS', 'Clovis', 0.01725),
  ('city', 'CA-COACHELLA', 'Coachella', 0.015),
  ('city', 'CA-COALINGA', 'Coalinga', 0.01725),
  ('city', 'CA-COLFAX', 'Colfax', 0),
  ('city', 'CA-COLMA', 'Colma', 0.02625),
  ('city', 'CA-COLTON', 'Colton', 0.015),
  ('city', 'CA-COLUSA', 'Colusa', 0.015),
  ('county', 'CA-COLUSA-COUNTY', 'Colusa County', 0.005),
  ('city', 'CA-COMPTON', 'Compton', 0.035),
  ('city', 'CA-CONCORD', 'Concord', 0.025),
  ('county', 'CA-CONTRA-COSTA-COUNTY', 'Contra Costa County', 0.015),
  ('city', 'CA-CORCORAN', 'Corcoran', 0.01),
  ('city', 'CA-CORNING', 'Corning', 0.005),
  ('city', 'CA-CORONA', 'Corona', 0.015),
  ('city', 'CA-CORONADO', 'Coronado', 0.005),
  ('city', 'CA-CORTE-MADERA', 'Corte Madera', 0.0175),
  ('city', 'CA-COSTA-MESA', 'Costa Mesa', 0.005),
  ('city', 'CA-COTATI', 'Cotati', 0.03),
  ('city', 'CA-COVINA', 'Covina', 0.0325),
  ('city', 'CA-CRESCENT-CITY', 'Crescent City', 0.01),
  ('city', 'CA-CUDAHY', 'Cudahy', 0.0325),
  ('city', 'CA-CULVER-CITY', 'Culver City', 0.035),
  ('city', 'CA-CUPERTINO', 'Cupertino', 0.025),
  ('city', 'CA-CYPRESS', 'Cypress', 0.005),
  ('city', 'CA-DALY-CITY', 'Daly City', 0.02625),
  ('city', 'CA-DANA-POINT', 'Dana Point', 0.005),
  ('city', 'CA-DANVILLE', 'Danville', 0.015),
  ('city', 'CA-DAVIS', 'Davis', 0.02),
  ('city', 'CA-DEL-MAR', 'Del Mar', 0.015),
  ('county', 'CA-DEL-NORTE-COUNTY-UNINCORPORATED-AREA', 'Del Norte County Unincorporated Area', 0.01),
  ('city', 'CA-DEL-REY-OAKS', 'Del Rey Oaks', 0.02),
  ('city', 'CA-DELANO', 'Delano', 0.01),
  ('city', 'CA-DESERT-HOT-SPRINGS', 'Desert Hot Springs', 0.015),
  ('city', 'CA-DIAMOND-BAR', 'Diamond Bar', 0.025),
  ('city', 'CA-DINUBA', 'Dinuba', 0.0125),
  ('city', 'CA-DIXON', 'Dixon', 0.01125),
  ('city', 'CA-DORRIS', 'Dorris', 0),
  ('city', 'CA-DOS-PALOS', 'Dos Palos', 0.01),
  ('city', 'CA-DOWNEY', 'Downey', 0.0325),
  ('city', 'CA-DUARTE', 'Duarte', 0.0325),
  ('city', 'CA-DUBLIN', 'Dublin', 0.03),
  ('city', 'CA-DUNSMUIR', 'Dunsmuir', 0.01),
  ('city', 'CA-EAST-PALO-ALTO', 'East Palo Alto', 0.02625),
  ('city', 'CA-EASTVALE', 'Eastvale', 0.005),
  ('city', 'CA-EL-CAJON', 'El Cajon', 0.01),
  ('city', 'CA-EL-CENTRO', 'El Centro', 0.01),
  ('city', 'CA-EL-CERRITO', 'El Cerrito', 0.03),
  ('county', 'CA-EL-DORADO-COUNTY', 'El Dorado County', 0),
  ('city', 'CA-EL-MONTE', 'El Monte', 0.0325),
  ('city', 'CA-EL-SEGUNDO', 'El Segundo', 0.025),
  ('city', 'CA-ELK-GROVE', 'Elk Grove', 0.015),
  ('city', 'CA-EMERYVILLE', 'Emeryville', 0.0325),
  ('city', 'CA-ENCINITAS', 'Encinitas', 0.005),
  ('city', 'CA-ESCALON', 'Escalon', 0.015),
  ('city', 'CA-ESCONDIDO', 'Escondido', 0.015),
  ('city', 'CA-ETNA', 'Etna', 0),
  ('city', 'CA-EUREKA', 'Eureka', 0.03),
  ('city', 'CA-EXETER', 'Exeter', 0.015),
  ('city', 'CA-FAIRFAX', 'Fairfax', 0.0175),
  ('city', 'CA-FAIRFIELD', 'Fairfield', 0.01125),
  ('city', 'CA-FARMERSVILLE', 'Farmersville', 0.015),
  ('city', 'CA-FERNDALE', 'Ferndale', 0.0225),
  ('city', 'CA-FILLMORE', 'Fillmore', 0),
  ('city', 'CA-FIREBAUGH', 'Firebaugh', 0.00725),
  ('city', 'CA-FOLSOM', 'Folsom', 0.005),
  ('city', 'CA-FONTANA', 'Fontana', 0.015),
  ('city', 'CA-FORT-BRAGG', 'Fort Bragg', 0.02),
  ('city', 'CA-FORT-JONES', 'Fort Jones', 0),
  ('city', 'CA-FORTUNA', 'Fortuna', 0.0225),
  ('city', 'CA-FOSTER-CITY', 'Foster City', 0.02125),
  ('city', 'CA-FOUNTAIN-VALLEY', 'Fountain Valley', 0.015),
  ('city', 'CA-FOWLER', 'Fowler', 0.01725),
  ('city', 'CA-FREMONT', 'Fremont', 0.03),
  ('city', 'CA-FRESNO', 'Fresno', 0.011),
  ('county', 'CA-FRESNO-COUNTY', 'Fresno County', 0.00725),
  ('city', 'CA-FULLERTON', 'Fullerton', 0.005),
  ('city', 'CA-GALT', 'Galt', 0.02),
  ('city', 'CA-GARDEN-GROVE', 'Garden Grove', 0.015),
  ('city', 'CA-GARDENA', 'Gardena', 0.0325),
  ('city', 'CA-GILROY', 'Gilroy', 0.025),
  ('city', 'CA-GLENDALE', 'Glendale', 0.0325),
  ('city', 'CA-GLENDORA', 'Glendora', 0.035),
  ('county', 'CA-GLENN-COUNTY', 'Glenn County', 0),
  ('city', 'CA-GOLETA', 'Goleta', 0.015),
  ('city', 'CA-GONZALES', 'Gonzales', 0.015),
  ('city', 'CA-GRAND-TERRACE', 'Grand Terrace', 0.005),
  ('city', 'CA-GRASS-VALLEY', 'Grass Valley', 0.01625),
  ('city', 'CA-GREENFIELD', 'Greenfield', 0.0225),
  ('city', 'CA-GRIDLEY', 'Gridley', 0.01),
  ('city', 'CA-GROVER-BEACH', 'Grover Beach', 0.015),
  ('city', 'CA-GUADALUPE', 'Guadalupe', 0.015),
  ('city', 'CA-GUSTINE', 'Gustine', 0.01),
  ('city', 'CA-HALF-MOON-BAY', 'Half Moon Bay', 0.02625),
  ('city', 'CA-HANFORD', 'Hanford', 0.01),
  ('city', 'CA-HAWAIIAN-GARDENS', 'Hawaiian Gardens', 0.0325),
  ('city', 'CA-HAWTHORNE', 'Hawthorne', 0.0325),
  ('city', 'CA-HAYWARD', 'Hayward', 0.035),
  ('city', 'CA-HEALDSBURG', 'Healdsburg', 0.025),
  ('city', 'CA-HEMET', 'Hemet', 0.015),
  ('city', 'CA-HERCULES', 'Hercules', 0.02),
  ('city', 'CA-HERMOSA-BEACH', 'Hermosa Beach', 0.025),
  ('city', 'CA-HESPERIA', 'Hesperia', 0.005),
  ('city', 'CA-HIDDEN-HILLS', 'Hidden Hills', 0.025),
  ('city', 'CA-HIGHLAND', 'Highland', 0.005),
  ('city', 'CA-HILLSBOROUGH', 'Hillsborough', 0.02125),
  ('city', 'CA-HOLLISTER', 'Hollister', 0.02),
  ('city', 'CA-HOLTVILLE', 'Holtville', 0.005),
  ('city', 'CA-HUGHSON', 'Hughson', 0.00625),
  ('county', 'CA-HUMBOLDT-COUNTY', 'Humboldt County', 0.015),
  ('city', 'CA-HUNTINGTON-BEACH', 'Huntington Beach', 0.005),
  ('city', 'CA-HUNTINGTON-PARK', 'Huntington Park', 0.0325),
  ('city', 'CA-HURON', 'Huron', 0.01725),
  ('city', 'CA-IMPERIAL', 'Imperial', 0.005),
  ('city', 'CA-IMPERIAL-BEACH', 'Imperial Beach', 0.015),
  ('county', 'CA-IMPERIAL-COUNTY', 'Imperial County', 0.005),
  ('city', 'CA-INDIAN-WELLS', 'Indian Wells', 0.005),
  ('city', 'CA-INDIO', 'Indio', 0.015),
  ('city', 'CA-INGLEWOOD', 'Inglewood', 0.03),
  ('county', 'CA-INYO-COUNTY', 'Inyo County', 0.005),
  ('city', 'CA-IONE', 'Ione', 0.005),
  ('city', 'CA-IRVINE', 'Irvine', 0.005),
  ('city', 'CA-IRWINDALE', 'Irwindale', 0.035),
  ('city', 'CA-ISLETON', 'Isleton', 0.015),
  ('city', 'CA-JACKSON', 'Jackson', 0.005),
  ('city', 'CA-JURUPA-VALLEY', 'Jurupa Valley', 0.005),
  ('city', 'CA-KERMAN', 'Kerman', 0.01725),
  ('county', 'CA-KERN-COUNTY-UNINCORPORATED-AREA', 'Kern County Unincorporated Area', 0.01),
  ('city', 'CA-KING-CITY', 'King City', 0.015),
  ('county', 'CA-KINGS-COUNTY', 'Kings County', 0),
  ('city', 'CA-KINGSBURG', 'Kingsburg', 0.01725),
  ('city', 'CA-LA-CANADA-FLINTRIDGE', 'La Cañada Flintridge', 0.0325),
  ('city', 'CA-LA-HABRA', 'La Habra', 0.015),
  ('city', 'CA-LA-HABRA-HEIGHTS', 'La Habra Heights', 0.025),
  ('city', 'CA-LA-MESA', 'La Mesa', 0.0125),
  ('city', 'CA-LA-MIRADA', 'La Mirada', 0.025),
  ('city', 'CA-LA-PALMA', 'La Palma', 0.015),
  ('city', 'CA-LA-PUENTE', 'La Puente', 0.03),
  ('city', 'CA-LA-QUINTA', 'La Quinta', 0.015),
  ('city', 'CA-LA-VERNE', 'La Verne', 0.0325),
  ('city', 'CA-LAFAYETTE', 'Lafayette', 0.02),
  ('city', 'CA-LAGUNA-BEACH', 'Laguna Beach', 0.005),
  ('city', 'CA-LAGUNA-HILLS', 'Laguna Hills', 0.005),
  ('city', 'CA-LAGUNA-NIGUEL', 'Laguna Niguel', 0.005),
  ('city', 'CA-LAGUNA-WOODS', 'Laguna Woods', 0.005),
  ('county', 'CA-LAKE-COUNTY', 'Lake County', 0),
  ('city', 'CA-LAKE-ELSINORE', 'Lake Elsinore', 0.015),
  ('city', 'CA-LAKE-FOREST', 'Lake Forest', 0.005),
  ('city', 'CA-LAKEPORT', 'Lakeport', 0.015),
  ('city', 'CA-LAKEWOOD', 'Lakewood', 0.0325),
  ('city', 'CA-LANCASTER', 'Lancaster', 0.04),
  ('city', 'CA-LARKSPUR', 'Larkspur', 0.02),
  ('county', 'CA-LASSEN-COUNTY', 'Lassen County', 0),
  ('city', 'CA-LATHROP', 'Lathrop', 0.015),
  ('city', 'CA-LAWNDALE', 'Lawndale', 0.0325),
  ('city', 'CA-LEMON-GROVE', 'Lemon Grove', 0.015),
  ('city', 'CA-LEMOORE', 'Lemoore', 0.01),
  ('city', 'CA-LINCOLN', 'Lincoln', 0),
  ('city', 'CA-LINDSAY', 'Lindsay', 0.015),
  ('city', 'CA-LIVE-OAK', 'Live Oak', 0),
  ('city', 'CA-LIVERMORE', 'Livermore', 0.03),
  ('city', 'CA-LIVINGSTON', 'Livingston', 0.015),
  ('city', 'CA-LODI', 'Lodi', 0.01),
  ('city', 'CA-LOMA-LINDA', 'Loma Linda', 0.005),
  ('city', 'CA-LOMITA', 'Lomita', 0.0325),
  ('city', 'CA-LOMPOC', 'Lompoc', 0.015),
  ('city', 'CA-LONG-BEACH', 'Long Beach', 0.0325),
  ('city', 'CA-LOOMIS', 'Loomis', 0.0025),
  ('city', 'CA-LOS-ALAMITOS', 'Los Alamitos', 0.02),
  ('city', 'CA-LOS-ALTOS', 'Los Altos', 0.025),
  ('city', 'CA-LOS-ALTOS-HILLS', 'Los Altos Hills', 0.025),
  ('city', 'CA-LOS-ANGELES', 'Los Angeles', 0.025),
  ('county', 'CA-LOS-ANGELES-COUNTY', 'Los Angeles County', 0.025),
  ('city', 'CA-LOS-BANOS', 'Los Banos', 0.015),
  ('city', 'CA-LOS-GATOS', 'Los Gatos', 0.02625),
  ('city', 'CA-LOYALTON', 'Loyalton', 0),
  ('city', 'CA-LYNWOOD', 'Lynwood', 0.035),
  ('city', 'CA-MADERA', 'Madera', 0.01),
  ('county', 'CA-MADERA-COUNTY', 'Madera County', 0.005),
  ('city', 'CA-MALIBU', 'Malibu', 0.03),
  ('city', 'CA-MAMMOTH-LAKES', 'Mammoth Lakes', 0.005),
  ('city', 'CA-MANHATTAN-BEACH', 'Manhattan Beach', 0.03),
  ('city', 'CA-MANTECA', 'Manteca', 0.0175),
  ('city', 'CA-MARICOPA', 'Maricopa', 0.01),
  ('county', 'CA-MARIN-COUNTY', 'Marin County', 0.01),
  ('city', 'CA-MARINA', 'Marina', 0.02),
  ('county', 'CA-MARIPOSA-COUNTY', 'Mariposa County', 0.01),
  ('city', 'CA-MARTINEZ', 'Martinez', 0.025),
  ('city', 'CA-MARYSVILLE', 'Marysville', 0.01),
  ('city', 'CA-MAYWOOD', 'Maywood', 0.025),
  ('city', 'CA-MCFARLAND', 'McFarland', 0.02),
  ('county', 'CA-MENDOCINO-COUNTY', 'Mendocino County', 0.00625),
  ('city', 'CA-MENDOTA', 'Mendota', 0.01975),
  ('city', 'CA-MENIFEE', 'Menifee', 0.015),
  ('city', 'CA-MENLO-PARK', 'Menlo Park', 0.02125),
  ('city', 'CA-MERCED', 'Merced', 0.01),
  ('county', 'CA-MERCED-COUNTY', 'Merced County', 0.005),
  ('city', 'CA-MILL-VALLEY', 'Mill Valley', 0.02),
  ('city', 'CA-MILLBRAE', 'Millbrae', 0.02125),
  ('city', 'CA-MILPITAS', 'Milpitas', 0.0275),
  ('city', 'CA-MISSION-VIEJO', 'Mission Viejo', 0.005),
  ('city', 'CA-MODESTO', 'Modesto', 0.01625),
  ('county', 'CA-MODOC-COUNTY', 'Modoc County', 0),
  ('county', 'CA-MONO-COUNTY', 'Mono County', 0),
  ('city', 'CA-MONROVIA', 'Monrovia', 0.0325),
  ('city', 'CA-MONTAGUE', 'Montague', 0),
  ('city', 'CA-MONTCLAIR', 'Montclair', 0.0175),
  ('city', 'CA-MONTE-SERENO', 'Monte Sereno', 0.025),
  ('city', 'CA-MONTEBELLO', 'Montebello', 0.0325),
  ('city', 'CA-MONTEREY', 'Monterey', 0.02),
  ('county', 'CA-MONTEREY-COUNTY-UNINCORPORATED-AREA', 'Monterey County Unincorporated Area', 0.015),
  ('city', 'CA-MONTEREY-PARK', 'Monterey Park', 0.0325),
  ('city', 'CA-MOORPARK', 'Moorpark', 0),
  ('city', 'CA-MORAGA', 'Moraga', 0.025),
  ('city', 'CA-MORENO-VALLEY', 'Moreno Valley', 0.015),
  ('city', 'CA-MORGAN-HILL', 'Morgan Hill', 0.025),
  ('city', 'CA-MORRO-BAY', 'Morro Bay', 0.015),
  ('city', 'CA-MOUNT-SHASTA', 'Mount Shasta', 0.0025),
  ('city', 'CA-MOUNTAIN-HOUSE', 'Mountain House', 0.005),
  ('city', 'CA-MOUNTAIN-VIEW', 'Mountain View', 0.025),
  ('city', 'CA-MURRIETA', 'Murrieta', 0.015),
  ('city', 'CA-NAPA', 'Napa', 0.015),
  ('county', 'CA-NAPA-COUNTY', 'Napa County', 0.005),
  ('city', 'CA-NATIONAL-CITY', 'National City', 0.015),
  ('city', 'CA-NEEDLES', 'Needles', 0.005),
  ('city', 'CA-NEVADA-CITY', 'Nevada City', 0.01625),
  ('county', 'CA-NEVADA-COUNTY', 'Nevada County', 0.0025),
  ('city', 'CA-NEWARK', 'Newark', 0.035),
  ('city', 'CA-NEWMAN', 'Newman', 0.00625),
  ('city', 'CA-NEWPORT-BEACH', 'Newport Beach', 0.005),
  ('city', 'CA-NORCO', 'Norco', 0.015),
  ('city', 'CA-NORWALK', 'Norwalk', 0.0325),
  ('city', 'CA-NOVATO', 'Novato', 0.02),
  ('city', 'CA-OAKDALE', 'Oakdale', 0.01125),
  ('city', 'CA-OAKLAND', 'Oakland', 0.035),
  ('city', 'CA-OAKLEY', 'Oakley', 0.015),
  ('city', 'CA-OCEANSIDE', 'Oceanside', 0.01),
  ('city', 'CA-OJAI', 'Ojai', 0),
  ('city', 'CA-ONTARIO', 'Ontario', 0.015),
  ('city', 'CA-ORANGE', 'Orange', 0.005),
  ('county', 'CA-ORANGE-COUNTY', 'Orange County', 0.005),
  ('city', 'CA-ORANGE-COVE', 'Orange Cove', 0.00725),
  ('city', 'CA-ORINDA', 'Orinda', 0.025),
  ('city', 'CA-ORLAND', 'Orland', 0.01),
  ('city', 'CA-OROVILLE', 'Oroville', 0.02),
  ('city', 'CA-OXNARD', 'Oxnard', 0.02),
  ('city', 'CA-PACIFIC-GROVE', 'Pacific Grove', 0.02),
  ('city', 'CA-PACIFICA', 'Pacifica', 0.02625),
  ('city', 'CA-PALM-DESERT', 'Palm Desert', 0.015),
  ('city', 'CA-PALM-SPRINGS', 'Palm Springs', 0.02),
  ('city', 'CA-PALMDALE', 'Palmdale', 0.04),
  ('city', 'CA-PALO-ALTO', 'Palo Alto', 0.025),
  ('city', 'CA-PALOS-VERDES-ESTATES', 'Palos Verdes Estates', 0.025),
  ('city', 'CA-PARADISE', 'Paradise', 0.015),
  ('city', 'CA-PARAMOUNT', 'Paramount', 0.0325),
  ('city', 'CA-PARLIER', 'Parlier', 0.01725),
  ('city', 'CA-PASADENA', 'Pasadena', 0.0325),
  ('city', 'CA-PASO-ROBLES', 'Paso Robles', 0.015),
  ('city', 'CA-PATTERSON', 'Patterson', 0.00625),
  ('city', 'CA-PERRIS', 'Perris', 0.005),
  ('city', 'CA-PETALUMA', 'Petaluma', 0.03),
  ('city', 'CA-PICO-RIVERA', 'Pico Rivera', 0.035),
  ('city', 'CA-PIEDMONT', 'Piedmont', 0.03),
  ('city', 'CA-PINOLE', 'Pinole', 0.03),
  ('city', 'CA-PISMO-BEACH', 'Pismo Beach', 0.01),
  ('city', 'CA-PITTSBURG', 'Pittsburg', 0.02),
  ('city', 'CA-PLACENTIA', 'Placentia', 0.015),
  ('county', 'CA-PLACER-COUNTY', 'Placer County', 0),
  ('city', 'CA-PLACERVILLE', 'Placerville', 0.01),
  ('city', 'CA-PLEASANT-HILL', 'Pleasant Hill', 0.02),
  ('city', 'CA-PLEASANTON', 'Pleasanton', 0.03),
  ('county', 'CA-PLUMAS-COUNTY', 'Plumas County', 0),
  ('city', 'CA-PLYMOUTH', 'Plymouth', 0.005),
  ('city', 'CA-POINT-ARENA', 'Point Arena', 0.02),
  ('city', 'CA-POMONA', 'Pomona', 0.0325),
  ('city', 'CA-PORT-HUENEME', 'Port Hueneme', 0.015),
  ('city', 'CA-PORTERVILLE', 'Porterville', 0.02),
  ('city', 'CA-PORTOLA', 'Portola', 0),
  ('city', 'CA-PORTOLA-VALLEY', 'Portola Valley', 0.02125),
  ('city', 'CA-POWAY', 'Poway', 0.005),
  ('city', 'CA-RANCHO-CORDOVA', 'Rancho Cordova', 0.015),
  ('city', 'CA-RANCHO-CUCAMONGA', 'Rancho Cucamonga', 0.005),
  ('city', 'CA-RANCHO-MIRAGE', 'Rancho Mirage', 0.005),
  ('city', 'CA-RANCHO-PALOS-VERDES', 'Rancho Palos Verdes', 0.025),
  ('city', 'CA-RANCHO-SANTA-MARGARITA', 'Rancho Santa Margarita', 0.005),
  ('city', 'CA-RED-BLUFF', 'Red Bluff', 0.0025),
  ('city', 'CA-REDDING', 'Redding', 0),
  ('city', 'CA-REDLANDS', 'Redlands', 0.015),
  ('city', 'CA-REDONDO-BEACH', 'Redondo Beach', 0.025),
  ('city', 'CA-REDWOOD-CITY', 'Redwood City', 0.02625),
  ('city', 'CA-REEDLEY', 'Reedley', 0.01975),
  ('city', 'CA-RIALTO', 'Rialto', 0.005),
  ('city', 'CA-RICHMOND', 'Richmond', 0.025),
  ('city', 'CA-RIDGECREST', 'Ridgecrest', 0.02),
  ('city', 'CA-RIO-DELL', 'Rio Dell', 0.0225),
  ('city', 'CA-RIO-VISTA', 'Rio Vista', 0.01875),
  ('city', 'CA-RIPON', 'Ripon', 0.005),
  ('city', 'CA-RIVERBANK', 'Riverbank', 0.00625),
  ('city', 'CA-RIVERSIDE', 'Riverside', 0.015),
  ('county', 'CA-RIVERSIDE-COUNTY', 'Riverside County', 0.005),
  ('city', 'CA-ROCKLIN', 'Rocklin', 0),
  ('city', 'CA-ROHNERT-PARK', 'Rohnert Park', 0.025),
  ('city', 'CA-ROLLING-HILLS', 'Rolling Hills', 0.025),
  ('city', 'CA-ROLLING-HILLS-ESTATES', 'Rolling Hills Estates', 0.025),
  ('city', 'CA-ROSEMEAD', 'Rosemead', 0.025),
  ('city', 'CA-ROSEVILLE', 'Roseville', 0.005),
  ('city', 'CA-ROSS', 'Ross', 0.01),
  ('city', 'CA-SACRAMENTO', 'Sacramento', 0.015),
  ('county', 'CA-SACRAMENTO-COUNTY', 'Sacramento County', 0.005),
  ('city', 'CA-SALINAS', 'Salinas', 0.02),
  ('city', 'CA-SAN-ANSELMO', 'San Anselmo', 0.02),
  ('county', 'CA-SAN-BENITO-COUNTY', 'San Benito County', 0.01),
  ('city', 'CA-SAN-BERNARDINO', 'San Bernardino', 0.015),
  ('county', 'CA-SAN-BERNARDINO-COUNTY', 'San Bernardino County', 0.005),
  ('city', 'CA-SAN-BRUNO', 'San Bruno', 0.02625),
  ('city', 'CA-SAN-CARLOS', 'San Carlos', 0.02125),
  ('city', 'CA-SAN-CLEMENTE', 'San Clemente', 0.005),
  ('city', 'CA-SAN-DIEGO', 'San Diego', 0.005),
  ('county', 'CA-SAN-DIEGO-COUNTY', 'San Diego County', 0.005),
  ('city', 'CA-SAN-DIMAS', 'San Dimas', 0.025),
  ('city', 'CA-SAN-FERNANDO', 'San Fernando', 0.0325),
  ('city', 'CA-SAN-FRANCISCO', 'San Francisco', 0.01375),
  ('county', 'CA-SAN-FRANCISCO-COUNTY', 'San Francisco County', 0.01375),
  ('city', 'CA-SAN-GABRIEL', 'San Gabriel', 0.0325),
  ('city', 'CA-SAN-JACINTO', 'San Jacinto', 0.015),
  ('city', 'CA-SAN-JOAQUIN', 'San Joaquin', 0.00725),
  ('county', 'CA-SAN-JOAQUIN-COUNTY', 'San Joaquin County', 0.005),
  ('city', 'CA-SAN-JOSE', 'San Jose', 0.0275),
  ('city', 'CA-SAN-JUAN-BAUTISTA', 'San Juan Bautista', 0.0175),
  ('city', 'CA-SAN-JUAN-CAPISTRANO', 'San Juan Capistrano', 0.005),
  ('city', 'CA-SAN-LEANDRO', 'San Leandro', 0.035),
  ('city', 'CA-SAN-LUIS-OBISPO', 'San Luis Obispo', 0.015),
  ('county', 'CA-SAN-LUIS-OBISPO-COUNTY', 'San Luis Obispo County', 0),
  ('city', 'CA-SAN-MARCOS', 'San Marcos', 0.015),
  ('city', 'CA-SAN-MARINO', 'San Marino', 0.025),
  ('city', 'CA-SAN-MATEO', 'San Mateo', 0.02375),
  ('county', 'CA-SAN-MATEO-COUNTY', 'San Mateo County', 0.02125),
  ('city', 'CA-SAN-PABLO', 'San Pablo', 0.0225),
  ('city', 'CA-SAN-RAFAEL', 'San Rafael', 0.02),
  ('city', 'CA-SAN-RAMON', 'San Ramon', 0.025),
  ('city', 'CA-SAND-CITY', 'Sand City', 0.02),
  ('city', 'CA-SANGER', 'Sanger', 0.01475),
  ('city', 'CA-SANTA-ANA', 'Santa Ana', 0.02),
  ('city', 'CA-SANTA-BARBARA', 'Santa Barbara', 0.02),
  ('county', 'CA-SANTA-BARBARA-COUNTY', 'Santa Barbara County', 0.005),
  ('city', 'CA-SANTA-CLARA', 'Santa Clara', 0.025),
  ('county', 'CA-SANTA-CLARA-COUNTY', 'Santa Clara County', 0.025),
  ('city', 'CA-SANTA-CLARITA', 'Santa Clarita', 0.025),
  ('city', 'CA-SANTA-CRUZ', 'Santa Cruz', 0.025),
  ('county', 'CA-SANTA-CRUZ-COUNTY-UNINCORPORATED-AREA', 'Santa Cruz County Unincorporated Area', 0.0225),
  ('city', 'CA-SANTA-FE-SPRINGS', 'Santa Fe Springs', 0.0375),
  ('city', 'CA-SANTA-MARIA', 'Santa Maria', 0.015),
  ('city', 'CA-SANTA-MONICA', 'Santa Monica', 0.035),
  ('city', 'CA-SANTA-PAULA', 'Santa Paula', 0.02),
  ('city', 'CA-SANTA-ROSA', 'Santa Rosa', 0.0275),
  ('city', 'CA-SANTEE', 'Santee', 0.005),
  ('city', 'CA-SARATOGA', 'Saratoga', 0.025),
  ('city', 'CA-SAUSALITO', 'Sausalito', 0.02),
  ('city', 'CA-SCOTTS-VALLEY', 'Scotts Valley', 0.025),
  ('city', 'CA-SEAL-BEACH', 'Seal Beach', 0.02),
  ('city', 'CA-SEASIDE', 'Seaside', 0.02),
  ('city', 'CA-SEBASTOPOL', 'Sebastopol', 0.0325),
  ('city', 'CA-SELMA', 'Selma', 0.01225),
  ('city', 'CA-SHAFTER', 'Shafter', 0),
  ('county', 'CA-SHASTA-COUNTY', 'Shasta County', 0),
  ('city', 'CA-SHASTA-LAKE', 'Shasta Lake', 0),
  ('county', 'CA-SIERRA-COUNTY', 'Sierra County', 0),
  ('city', 'CA-SIERRA-MADRE', 'Sierra Madre', 0.0325),
  ('city', 'CA-SIGNAL-HILL', 'Signal Hill', 0.0325),
  ('city', 'CA-SIMI-VALLEY', 'Simi Valley', 0),
  ('county', 'CA-SISKIYOU-COUNTY', 'Siskiyou County', 0),
  ('city', 'CA-SOLANA-BEACH', 'Solana Beach', 0.015),
  ('county', 'CA-SOLANO-COUNTY', 'Solano County', 0.00125),
  ('city', 'CA-SOLEDAD', 'Soledad', 0.02),
  ('city', 'CA-SOLVANG', 'Solvang', 0.015),
  ('city', 'CA-SONOMA', 'Sonoma', 0.03),
  ('county', 'CA-SONOMA-COUNTY', 'Sonoma County', 0.02),
  ('city', 'CA-SONORA', 'Sonora', 0.015),
  ('city', 'CA-SOUTH-EL-MONTE', 'South El Monte', 0.035),
  ('city', 'CA-SOUTH-GATE', 'South Gate', 0.035),
  ('city', 'CA-SOUTH-LAKE-TAHOE', 'South Lake Tahoe', 0.015),
  ('city', 'CA-SOUTH-PASADENA', 'South Pasadena', 0.0325),
  ('city', 'CA-SOUTH-SAN-FRANCISCO', 'South San Francisco', 0.02625),
  ('city', 'CA-ST-HELENA', 'St. Helena', 0.01),
  ('county', 'CA-STANISLAUS-COUNTY', 'Stanislaus County', 0.00625),
  ('city', 'CA-STANTON', 'Stanton', 0.015),
  ('city', 'CA-STOCKTON', 'Stockton', 0.0175),
  ('city', 'CA-SUISUN-CITY', 'Suisun City', 0.01875),
  ('city', 'CA-SUNNYVALE', 'Sunnyvale', 0.025),
  ('city', 'CA-SUSANVILLE', 'Susanville', 0.01),
  ('county', 'CA-SUTTER-COUNTY', 'Sutter County', 0),
  ('city', 'CA-SUTTER-CREEK', 'Sutter Creek', 0.015),
  ('city', 'CA-TAFT', 'Taft', 0.01),
  ('city', 'CA-TEHACHAPI', 'Tehachapi', 0.01),
  ('city', 'CA-TEHAMA', 'Tehama', 0),
  ('county', 'CA-TEHAMA-COUNTY', 'Tehama County', 0),
  ('city', 'CA-TEMECULA', 'Temecula', 0.015),
  ('city', 'CA-TEMPLE-CITY', 'Temple City', 0.025),
  ('city', 'CA-THOUSAND-OAKS', 'Thousand Oaks', 0),
  ('city', 'CA-TIBURON', 'Tiburon', 0.01),
  ('city', 'CA-TORRANCE', 'Torrance', 0.03),
  ('city', 'CA-TRACY', 'Tracy', 0.01),
  ('city', 'CA-TRINIDAD', 'Trinidad', 0.0225),
  ('county', 'CA-TRINITY-COUNTY', 'Trinity County', 0),
  ('city', 'CA-TRUCKEE', 'Truckee', 0.0175),
  ('city', 'CA-TULARE', 'Tulare', 0.01),
  ('county', 'CA-TULARE-COUNTY', 'Tulare County', 0.005),
  ('city', 'CA-TULELAKE', 'Tulelake', 0),
  ('county', 'CA-TUOLUMNE-COUNTY', 'Tuolumne County', 0),
  ('city', 'CA-TURLOCK', 'Turlock', 0.01375),
  ('city', 'CA-TUSTIN', 'Tustin', 0.005),
  ('city', 'CA-TWENTYNINE-PALMS', 'Twentynine Palms', 0.005),
  ('city', 'CA-UKIAH', 'Ukiah', 0.01625),
  ('city', 'CA-UNION-CITY', 'Union City', 0.035),
  ('city', 'CA-UPLAND', 'Upland', 0.005),
  ('city', 'CA-VACAVILLE', 'Vacaville', 0.00875),
  ('city', 'CA-VALLEJO', 'Vallejo', 0.02),
  ('city', 'CA-VENTURA', 'Ventura', 0.005),
  ('county', 'CA-VENTURA-COUNTY', 'Ventura County', 0),
  ('city', 'CA-VERNON', 'Vernon', 0.0325),
  ('city', 'CA-VICTORVILLE', 'Victorville', 0.015),
  ('city', 'CA-VILLA-PARK', 'Villa Park', 0.005),
  ('city', 'CA-VISALIA', 'Visalia', 0.0125),
  ('city', 'CA-VISTA', 'Vista', 0.01),
  ('city', 'CA-WALNUT', 'Walnut', 0.025),
  ('city', 'CA-WALNUT-CREEK', 'Walnut Creek', 0.02),
  ('city', 'CA-WASCO', 'Wasco', 0.01),
  ('city', 'CA-WATERFORD', 'Waterford', 0.00625),
  ('city', 'CA-WATSONVILLE', 'Watsonville', 0.025),
  ('city', 'CA-WEED', 'Weed', 0.0025),
  ('city', 'CA-WEST-COVINA', 'West Covina', 0.025),
  ('city', 'CA-WEST-HOLLYWOOD', 'West Hollywood', 0.0325),
  ('city', 'CA-WEST-SACRAMENTO', 'West Sacramento', 0.02),
  ('city', 'CA-WESTLAKE-VILLAGE', 'Westlake Village', 0.025),
  ('city', 'CA-WESTMINSTER', 'Westminster', 0.02),
  ('city', 'CA-WESTMORLAND', 'Westmorland', 0.005),
  ('city', 'CA-WHEATLAND', 'Wheatland', 0.005),
  ('city', 'CA-WHITTIER', 'Whittier', 0.0325),
  ('city', 'CA-WILDOMAR', 'Wildomar', 0.015),
  ('city', 'CA-WILLIAMS', 'Williams', 0.01),
  ('city', 'CA-WILLITS', 'Willits', 0.01875),
  ('city', 'CA-WILLOWS', 'Willows', 0.015),
  ('city', 'CA-WINDSOR', 'Windsor', 0.02),
  ('city', 'CA-WINTERS', 'Winters', 0.01),
  ('city', 'CA-WOODLAKE', 'Woodlake', 0.015),
  ('city', 'CA-WOODLAND', 'Woodland', 0.0075),
  ('city', 'CA-WOODSIDE', 'Woodside', 0.02125),
  ('county', 'CA-YOLO-COUNTY', 'Yolo County', 0),
  ('city', 'CA-YORBA-LINDA', 'Yorba Linda', 0.005),
  ('city', 'CA-YOUNTVILLE', 'Yountville', 0.005),
  ('city', 'CA-YREKA', 'Yreka', 0.015),
  ('city', 'CA-YUBA-CITY', 'Yuba City', 0),
  ('county', 'CA-YUBA-COUNTY-UNINCORPORATED-AREA', 'Yuba County Unincorporated Area', 0.01),
  ('city', 'CA-YUCAIPA', 'Yucaipa', 0.015),
  ('city', 'CA-YUCCA-VALLEY', 'Yucca Valley', 0.015);

-- The locations themselves, hung off California rather than off their county:
-- CDTFA's city figure already includes any county district applying there, so
-- a city nested under its county would count that district twice.
INSERT INTO tax_jurisdiction (parent_id, country, level, code, name)
SELECT ca.id, 'us', l.level, l.code, l.name
FROM cdtfa_load l
CROSS JOIN (
  SELECT id FROM tax_jurisdiction
  WHERE country = 'us' AND level = 'state' AND code = 'CA'
) ca
ON CONFLICT (country, level, code) DO NOTHING;

-- One rate per location. California's own 7.25% row is untouched: it has been
-- in force since 2017 and this schedule does not change it, and a second row
-- for the same date range would fail tax_rate_no_overlap anyway.
INSERT INTO tax_jurisdiction_rate
  (jurisdiction_id, treatment, rate, effective_from,
   source_authority, source_document, source_url, notes)
SELECT j.id, 'taxable', l.rate, DATE '2026-07-01',
       'cdtfa',
       'CDTFA California City & County Sales & Use Tax Rates, effective '
       'July 1, 2026 (SalesTaxRates07-01-26.xlsx)',
       'https://www.cdtfa.ca.gov/taxes-and-fees/sales-use-tax-rates.htm',
       'This location''s own share: the combined rate CDTFA publishes for it '
       'less the statewide 7.25%, so the jurisdiction chain sums back to the '
       'published figure. Converted from the authority''s file by '
       'cmd/cdtfaimport on 2026-09-04. Unverified: nobody has yet confirmed '
       'the conversion against the published page.'
FROM cdtfa_load l
JOIN tax_jurisdiction j
  ON j.country = 'us' AND j.level = l.level AND j.code = l.code
ON CONFLICT DO NOTHING;
